### ISSUE TITLE
Don't allow create site test

### ISSUE THREAD

**Issue by topdown** [bradp/vv#100]
Not sure if this is more of a VVV issue or for VV
But creating site test should be killed right away with an error that site test is not allowed.

Reason is that there is a test database and it caused the whole site setup to complete except it errors out on database creation because the database already exists. So you end up with a site that has everything but the database installed.

**Comment by bradp** [comment]
I'm made a site called test before without a problem, I'm pretty sure. 

I'm also not seeing a test database existing in bare VVV. 

Did you encounter this on a new VVV instance?

**Comment by topdown** [comment]
Well it was an old VVV that I updated and used your script to remove old sites and then tested with test as a site and the MYSQL failed. Which is when I remembered that MySQL default install has a test database which would explain the failed install.

(Different issue) now looking in my database I also see databases for some of the old sites that I used VV to install.

**Comment by bradp** [comment]
Gonna close this, feel free to re-open if you see more issues.
