### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by vincentschroeder** [bradp/vv#101]
It would be great do extend the build script to select the language for the wordpress installation e.g. de_DE.

**Comment by bradp** [comment]
+1 to this. There's a way to do it with blueprints right now, but it really should be exposed either in the wizard or in a flag.

**Comment by mantismamita** [comment]
+1 This would be very helpful. I'll have to look at how to do it with blueprints in the meantime.

**Comment by bradp** [comment]
Just added this in 0e97ac174909.

There is now a `--locale` or a `--language` flag that you can use during site creation like so:  `vv create --locale` fr_FR`.

I'll be adding this to the repo and adding this to the next stable version.
