### ISSUE TITLE
Could use DB prefix setting

### ISSUE THREAD

**Issue by HongPong** [bradp/vv#102]
This project worked great for me. Only suggestion is that it could use an option in the setup to set the database prefix string. I was working with a custom prefix and it imported the DB dump correctly but I had to set the prefix string by hand in wp-config. Otherwise everything was fine, Very Very handy tool.

**Comment by bradp** [comment]
Not a bad idea! I can get that added in for sure.

**Comment by andrejm** [comment]
+1 for this. I'm changing table prefix regularly, would benefit from this.

**Comment by jiwicky** [comment]
+1 - would be an awesome addition.

**Comment by justintucker** [comment]
Just started using this. Prefix option would be great.

**Comment by bradp** [comment]
Added this in a854c1c8debae2ec2e5854531f07b73e75f24040.

When creating a site, simply add the `--prefix myprefix_` to `vv create` with any other flag you're using.

This will be in the next released version.

**Comment by jiwicky** [comment]
Super 100% awesome.

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.
