### ISSUE TITLE
Add option to download Search and Replace

### ISSUE THREAD

**Issue by robneu** [bradp/vv#104]
It would be nice to be able to automatically download this script into the site's root.

https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

**Comment by bradp** [comment]
I'll get this added as a flag, thanks!

**Comment by WPprodigy** [comment]
Ahh yes, love that script!

I haven't tried this one yet, but I've heard all good things: http://wp-cli.org/commands/search-replace/

**Comment by bradp** [comment]
Added the `--download-search-and-replace` flag for `vv create` in 63afc05d3b22bc21d05bf9213969ab2ce1eccae7 which will download the search/replace script into the site root. 

This will be in the next tagged released version

**Comment by robneu** [comment]
:heart_eyes:

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.
