### ISSUE TITLE
What is 'local SQL file to import' relative to?

### ISSUE THREAD

**Issue by josiahsprague** [bradp/vv#111]
During `vv create` I was prompted `Local SQL file to import for database (leave blank to skip):`, so I entered the name of a `.sql` file in the directory that I ran `vv create` from, but during installation I see `cp: my_wp_database.sql: No such file or directory`, and the site is installed without importing the database. Where does `vv` look for the `.sql` file to import? I can open a PR to add this information to the README, but I haven't been able to figure out where `vv` looks.

**Comment by bradp** [comment]
It needs to be an absolute path to the file on your host system.

**Comment by josiahsprague** [comment]
I tried the absolute path of `~/Vagrant/wordpress/my_wp_database.sql` and it still wasn't found. Do I have to do `/Users/Josiah/Vagrant/wordpress/my_wp_database.sql`?

**Comment by bradp** [comment]
You should be able to do either one. But I'd suggest trying the second one. The way I do it is I just drag the file into my terminal to autocomplete the path.

**Comment by josiahsprague** [comment]
Oh, that's a great tip. Didn't think of that. Thanks!

**Comment by zanematthew** [comment]
Did that work? Because for me after adding the path the db file is never used/imported.

**Comment by ciccarone** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212754-244506145_9-s4-v1.png?transparent=1&palette=1&width=246)

didn't work for me.  beautiful tool though
