### ISSUE TITLE
Error after vv create

### ISSUE THREAD

**Issue by rpasillas** [bradp/vv#112]
After running vv create in git bash, i get these errors and the URL doesn't work.

![capture](https://cloud.githubusercontent.com/assets/5605762/8047539/6e66d5c4-0dfb-11e5-9234-dfdb8f9e28a2.PNG)

**Comment by bradp** [comment]
Are you able to provision and use VVV without vv?

**Comment by rpasillas** [comment]
I am able to use VVV without VV.

**Comment by rpasillas** [comment]
This was on Windows 7 by the way.

**Comment by bradp** [comment]
Were the correct WP files created by vv? This seems to be a non-vv issue, as the errors happen on provision, and they aren't specific to anything that vv is doing.
