### ISSUE TITLE
 Removing default plugins - Akismet

### ISSUE THREAD

**Issue by WPprodigy** [bradp/vv#113]
When choosing to delete the default plugins, Akismet gets misspelled to "aksimet" and doesn't get deleted: 

![](http://cld.wthms.co/17qaT+)

**Comment by WPprodigy** [comment]
![](http://makeameme.org/media/created/one-does-not-biewm8.jpg)

**Comment by ThatGerber** [comment]
Fixed in https://github.com/bradp/vv/pull/109. You'll have to update VV or wait for the next release to Homebrew (if that's where you installed it from).

**Comment by WPprodigy** [comment]
Ahh, that explains why I found it spelled correctly in the code earlier. (And yep, good guess on Homebrew) Thanks!

**Comment by bradp** [comment]
I just need to tag a new release for brew installations. I have a few other features in progress, and I'm waiting until those are finished for the next version.

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.
