### ISSUE TITLE
site file lands in wrong instance of vvv - not multi vvv install compatible?

### ISSUE THREAD

**Issue by HongPong** [bradp/vv#115]
I tried to create a subdomain/multisite style WP site. It went into the first vvv instance I have used vv on, not the one from the vagrant-local directory that I am within on OSX. The problem is that ~/.vv-config has hard coded the directory that vv thinks it's operating in. 

I was able to get around this by removing ~/.vv-config .

I was warned in the "about to perform the following" that it was the old path for the other instance, but I didn't notice it. I'd suggest changing the documentation to reflect that this is the default behavior.

**Comment by bradp** [comment]
~/.vv-config is used to store the configuration of the VVV path, and a user is prompted for this path if VV can't automatically find an install of VVV. You can change the VVV path in ~/.vv-config or by using the `-fp` flag.
