### ISSUE TITLE
Yaml/Config instead of blueprint?

### ISSUE THREAD

**Issue by ThatGerber** [bradp/vv#120]
It would be great if there was a way to make more use of the vv-config or possibly a [YAML](https://en.wikipedia.org/?title=YAML) instead of JSON blueprints. It would be nice to be able to define all of the installation variables/flags in a YAML file and then override them with command line flags, where needed, especially for users who will be changing things a lot (like users who declare a different language on every install). I always use the latest WordPress version, and don't install WP-Content as a repo, and it would be great to override some of those flags on every install.

**Comment by jb510** [comment]
I know @bradp had plans to support HGV which uses YML for everything...  Wondering if it would make sense to build that from the ground up to use YML and then port that back over to VVV.

**Comment by bradp** [comment]
Blueprints will probably stick with JSON, but I want to add a way to define defaults for vv options.

Closing this, as the defaults tracking will happen here: https://github.com/bradp/vv/issues/161
