### ISSUE TITLE
Add ability to remove cruft left behind after site manually deleted

### ISSUE THREAD

**Issue by jb510** [bradp/vv#121]
Often I delete a folder from /VVV/www/{sitename} first...

Then later realize that there is still a bunch of .conf stuff left behind.  It'd be cool if VV had a way to remove that stuff.  

Specifically, nginx conf, init-custom sql and optionally the DB and DB dump.

I get frustrated because DB's for those sites, even if removed via PhpMyAdmin get recreated by init-custom.sql, and then re-imported from the mysql dump.  It makes "cleaning up" a PITA.

**Comment by bradp** [comment]
:+1: Great idea, this shouldn't be too difficult, as we can just modify the verification of the site existing before deletion.

**Comment by bradp** [comment]
Added in 4ce375086e7b, will be in next version
