### ISSUE TITLE
Official Bedrock Integration?

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [bradp/vv#126]
I'm just starting out on this, but I might be able to build a PR if interest.

Starting with:
https://github.com/julykaz/vvv-demo-1-bedrock

https://roots.io/bedrock/docs/

**Comment by bradp** [comment]
https://github.com/bradp/vv/pull/127 closes this

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.

**Comment by caseypatrickdriscoll** [comment]
+1 (and now a bit energized to maybe tackle some of the other features)
