### ISSUE TITLE
Non WordPress site creation.

### ISSUE THREAD

**Issue by christianmagill** [bradp/vv#128]
I love this tool!

I know this is a little out of scope, but I'd like to see an option or a command to automate site creation for non WordPress sites with an option to create a database.

Sometimes I have small non WordPress projects for landing pages and the like, and it would be great if I could create those installs as easily as you've made it for WordPress projects.

**Comment by bradp** [comment]
This is possible using either `vv create --blank-with-db`` or ``--blank```.

**Comment by christianmagill** [comment]
Much thanks!
