### ISSUE TITLE
Deployment Error on Directories

### ISSUE THREAD

**Issue by neilgee** [bradp/vv#129]
I am getting an error when using the deployment feature. The root files get copied across but when any directory is being copied via SFTP the error occurs.
```
vv -v push vagrant-stag
/opt/vagrant/embedded/gems/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open': Net::SFTP::StatusException open /home/vagrant/public_html/wp-admin/css/about-rtl.css (2, "no such file") (Net::SFTP::StatusException)
```
I can create and delete directories using the same credentials manually via SFTP.

**Comment by bradp** [comment]
This looks to be a Vagrant issue, not VV. [This issue](https://github.com/mitchellh/vagrant/issues/5095) seems very similar, please try the fixes they've listed there or try updating Vagrant.

**Comment by neilgee** [comment]
Yes, seen this and have added to the thread, same issue when upgraded to the latest Vagrant 1.7.2 - cant see any fixes at this point in time.
