### ISSUE TITLE
Feature Request: Adding the domain name to vv-install arguments and use it to replace string in Blueprint.json

### ISSUE THREAD

**Issue by 1bigidea** [bradp/vv#130]
One of the plugin I install often on VVV is Delicious Brains DB Migrate Pro. They support installation via composer if you pass the domain name as part of the URL (so they can update their installation count).[https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/]

If I could replace something like {domain} with a parameter passed to vv-install, then this would be a very useful extension to VV.

**Comment by 1bigidea** [comment]
duplicate

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.
