### ISSUE TITLE
Creating Site with Bedrock

### ISSUE THREAD

**Issue by cartogram** [bradp/vv#131]
Can't seem to pass the bedrock option to the create command.

`vv version 1.7.2`

`$ vv create --bedrock`

`[Error] Unknown option --bedrock`

What am I missing?

**Comment by bradp** [comment]
The bedrock issue doesn't exist in 1.7.2, only in 1.7.3 which I plan to release ASAP after some final testing.

**Comment by cartogram** [comment]
Ah Great, thanks Brad. Just noticed the PR and conversation there. Loving this tool BTW, Thanks!
