### ISSUE TITLE
Ability to install WordPress trunk

### ISSUE THREAD

**Issue by swissspidy** [bradp/vv#132]
Being able to install the latest trunk version of WordPress would be awesome. Presumably from GitHub or `https://wordpress.org/nightly-builds/wordpress-latest.zip`.

**Comment by caseypatrickdriscoll** [comment]
Can this be cloned locally from the trunk/development install in vvv?

**Comment by michaelryanmcneill** [comment]
@caseypatrickdriscoll, I think it would be better to be pulled directly from GitHub, SVN, or Nightly, as who knows what content has been changed in the `local.wordpress-trunk.dev` install. @swissspidy, I'll work on adding a patch for this and submitting a PR. 

(cc: @bradp)

**Comment by bradp** [comment]
Added in 515ddb36553a.

Also will update on each provision.  (And no dirty SVN junk)
