### ISSUE TITLE
vv delete or vv remove, then vv create with a fresh db?

### ISSUE THREAD

**Issue by huskycdn** [bradp/vv#133]
When I vv remove a site and then vv create a new one with the same details, I get the db from the original site I thought I had removed.

I'm not sure if I'm doing something wrong or if this is expected behaviour.  I'm new to vagrant, VVV and VV -- everything's newly installed.   

To get a completely fresh site after vv remove, it seems to be necessary to delete the db using phpMyAdmin (which is still there after vv remove) and the sql file in database/backups.

This came up because I'm trying to set up a site on my laptop, pulling everything from a git repo and a live db.  On the first try something went wrong with the migrated db on the laptop and broke the site.  I thought I could just vv remove and start again.  

Is this correct?  Is there a better way to do it so that everything, including the db, is removed with a vv remove?

**Comment by bradp** [comment]
If you run 'vv --version', what do you get? In the current version, the db should be removed automatically.

Also, are you re-provisioning after removing?

**Comment by huskycdn** [comment]
It's this, everything installed yesterday:
```
$ vv --version
vv version 1.7.2
$
```

I got vv from brew.

I thought ```vv create``` did ```vagrant up --provision```. 
I've only done ```vv create```, then ```vv remove```, then ```vv create```.

It looks to me like a .sql file from the db is put in the backups folder during ```vv remove``` and that's used on the second ```vv create```.  

By the way, the README.md refers to both ```vv delete``` and ```vv remove```, but I have assumed they are interchangeable.

**Comment by bradp** [comment]
Correct, both `vv delete` and `vv remove` are the same command internally. 

Are you running the vagrant hosts trigger plugin?

**Comment by huskycdn** [comment]
Hi, Sorry about the delay getting back to you.  It's taken a while til I had enough time to try out a few things.  

I've got the optional installs in the VVV instructions (vagrant-hostsupdater and vagrant-triggers). At first I thought I just needed to do something like:
`VAGRANT_NO_TRIGGERS vv create`
to get it to create a new site without the previous site's db.  This assumed it was recreating the DB from a back-up file, but I don't think it is.

Having looked at it again, it appears that 'vv remove' leaves behind the DB (and the trigger creates a backup.sql).  This then gets used in the subsequent `vv create`. If I manually delete the DB and the .sql file in the database/backups/, then it does create a new site with a fresh DB.

I don't recall deviating from the install instructions for VVV or VV and I haven't made any edits to `Vagrantfile`, so not sure why it's not cooperating.  It displays `Removing database` when executing `vv remove`, but the database still appears in PHPmyAdmin.

**Comment by bradp** [comment]
Can you send me a screenshot of the structure of the backups folder?

**Comment by bradp** [comment]
To answer the "not sure why it's not cooperating. It displays Removing database when executing vv remove" question - it is because the data in //database/data/SITENAME gets removed, but VVV's vagrant-triggers backup functionality is over-riding the default database handling.

I can modify vv to remove all database backups when deleting a site as well.

**Comment by huskycdn** [comment]
Hello Brad,
I hope this is what you're looking for.  The site I've been creating and removing is 'theaviary'.  Everything here should be default.  I just installed things using the instructions here and on the Vagrant and VVV pages.
```
MacBook:VVV $ ls
CHANGELOG.md       README.md          config             provision
CONTRIBUTING.md    Vagrantfile        database           wp-cli.yml
LICENSE            Vagrantfile-backup log                www
MacBook:VVV $ cd database/
MacBook:database $ ls
backups                import-sql.sh          init-custom.sql.sample
data                   init-custom.sql        init.sql
MacBook:database $ cd backups/
MacBook:backups $ ls
readme.txt            wordpress_default.sql wordpress_trunk.sql
theaviary.sql         wordpress_develop.sql
MacBook:backups $
```

Hope that helps,
Morgan

**Comment by neilgee** [comment]
> I can modify vv to remove all database backups when deleting a site as well.

I like this idea Brad , I use **vagrant triggers** and yes it restores the db backup stored in _/database/backups_ after having removed an instance with **vv delete**

**Comment by bradp** [comment]
Added in de40ea7c60a7
