### ISSUE TITLE
When using --images, should the server first check for the file locally before rewriting to proxy?

### ISSUE THREAD

**Issue by mishtershmart** [bradp/vv#134]
I've just started using VV and noticed that, when loading images by proxy, local images are ignored. This left me with 404s wherever I'd added an image to the local site, with the intention of pushing them later using *WP Migrate DB*.

I went and changed the .conf file so that it only loads by proxy if the file doesn't exist locally. I simply changed the location directive in my site's .conf file to the following;
````
location ~ ^/wp-content/uploads/(.*) { if (!-f $request_filename) { rewrite ^/wp-content/uploads/(.*)$ http://somedomain.com/wp-content/uploads/$1 redirect; } } }
````

I'll be doing this on all the sites I work on, so I'm wondering if this isn't something that VV should already do?

**Comment by bradp** [comment]
That is not a bad idea at all, I'll do some testing and get it changed over to that method, thanks!
