### ISSUE TITLE
Sample Content - Author is 0

### ISSUE THREAD

**Issue by JayWood** [bradp/vv#135]
When installing the sample content via `vv create` the author either is not set, or is set as 0.

Quick fix if you ran into this is to just run an SQL update query like so:
`mysql> update wp_posts set post_author = 1 where post_author = 0;`

Not a huge bug, and should probably be low-pri, but a bug nonetheless!

**Note:** Windows System!

**Comment by bradp** [comment]
Fixed in 871e9a16cb4bb7f0dd39cb8c351827c0eda37421.
