### ISSUE TITLE
Configure the default timezone and locale

### ISSUE THREAD

**Issue by ollietreend** [bradp/vv#138]
Hi,

Is it possible to configure the default timezone and locale for newly created sites?

I'm aware that I can use the `--locale` option when running `vv create`, which is half-way there. But what I'm looking for is the ability to configure the default locale (and timezone) so that I don't need to use command line options every time I create a new site.

Is this possible?

Thanks

**Comment by wp-entwickler-at** [comment]
I'm also looking for the same.
I'd suggest to add entries into the `~/.vv-config` file for both default locale and timezone.
The other option would be to put it into the blueprints, but I think most users will use the same settings for all their blueprints and you can always specify the locale on the command line if you want.

**Comment by bradp** [comment]
One of the things I want to add is the ability to define these defaults, in somewhere like ~/.vv-config. I'm thinking after you set up the first site, I'd ask if you want to save these as the default.

I'm also working on a 'hooks' system to easily extend vv functionality, which will allow for the timezone setting and configuration.

Great suggestions though, and I'm excited to get these implemented.

**Comment by bradp** [comment]
Closing this to track in the 2.0 release issue: https://github.com/bradp/vv/issues/161
