### ISSUE TITLE
Confirm VVV path when automagically finding it

### ISSUE THREAD

**Issue by bradp** [bradp/vv#139]
On first run of vv, there's a chance the wrong dir is found and used, causing some confusing issues for new users

**Comment by mikethrussell** [comment]
Confirmed. First run of vv discovered a Vagrantfile in the parent directory and continued to boot that box. A dialog such as: 'VVV located in "path/to/dir". Is this correct ? Y/N' would be useful.

**Comment by bradp** [comment]
Added in 64022771911e, will be in next version.
