### ISSUE TITLE
Import DB on VV create - vv changes file name and unknown path for sql file location

### ISSUE THREAD

**Issue by mikethrussell** [bradp/vv#140]
Create options were to import existing file. I'm chose backup.sql in home directory. vv dialog looks for "../domain.sql"

Error: Import file missing: ../domain.sql

Not explicit which path it's looking for - relative to folder in which vv -c was invoked, VVV installation or new domain within www folder?

**Comment by bradp** [comment]
The import DB question expects the full path to the DB on the host system.
