### ISSUE TITLE
vagrant ssh returns connection closed after vv create

### ISSUE THREAD

**Issue by robinloxley1** [bradp/vv#142]
I use vvv to init development site, and I can vagrant ssh without problems.(stable wordpress 4.3.0)
After using vv create with all default options except choosing wordpress "4.2.4".
I cann't "vagrant ssh". It says "connection to 127.0.0.1 closed". 

All sites are accessible from browser, including vv-created sites.
I still can vagrant ssh -c "commands" to return correct results.

I am using Mac OS 10.10.3, and I can repeat above process, by reinstalling vvv and folders.

**Comment by bradp** [comment]
This seems to be more of a vagrant or VVV issue.
