### ISSUE TITLE
Add support for WPStarter.

### ISSUE THREAD

**Issue by GaryJones** [bradp/vv#145]
Similar to Skeleton and Bedrock, it would be great if https://github.com/wecodemore/wpstarter had support in vv too.

**Comment by bradp** [comment]
Was just reading through the docs for this.

Couple questions for ya @GaryJones . I haven't ever used it, but just want to check what the best support for this would be. Should vv just create the default wp starter composer example, and then run the composer install? Or should I build out some prompts for the different parts to it?

**Comment by GaryJones** [comment]
Pinging @gmazzap for his view. 

One idea is just to have a vv prompt that asked where an existing composer.json is, copy that into htdocs and run `composer install`. 

As a later potential implementation, if the first prompt is skipped, then ask the questions to build it out, though this could be fine with `composer init` before running vv.

**Comment by bradp** [comment]
Closing this to track in the 2.0 release issue: #161
