### ISSUE TITLE
Unknown option --show-hooks

### ISSUE THREAD

**Issue by daltonrooney** [bradp/vv#147]
I'm trying to run a script using a hook, but the script doesn't seem to be running. I created a folder called vv in vagrant-local and named the file post_site_creation_finished but it's never loaded. 

When I run the command vv create --show-hooks I receive an error:
[Error] Unknown option --show-hooks

vv --version outputs: vv version 1.8.0
vv --debug-vv outputs: [Error] Unknown option --debug-vv

Installed vv this morning via brew. Any suggestions?

**Comment by bradp** [comment]
Those features aren't in the stable version yet. 1.8 is on Brew, and 1.9 will have those features. Should be released soon.
