### ISSUE TITLE
Create unit-testing-ready site?

### ISSUE THREAD

**Issue by mnelson4** [bradp/vv#148]
Very handy tool, thanks!
Is it currently possible to use this tool to create a wordpress site using the git://develop.git.wordpress.org/ repository instead of https://github.com/wordpress/wordpress ?
It would be nice because that repository has the `tests` folder which is necessary for running unit tests. And if it's not currently possible, any suggestions on what I'd need to tweak to do that?
I imagine the main hurdle to using this other repo is that it also adds a `src` folder so many of the paths would need to be changed right?

**Comment by ThatGerber** [comment]
@mnelson4 You might look into WP CLI's Scaffold functions: http://wp-cli.org/commands/scaffold/

This project is really starting to suffer from scope-creep and is going against the [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) of focusing on doing one thing and doing it well. The commands are getting difficult to remember and configure correctly.

Adding sites to a VVV setup, configuring the server and setting up the DB, those are things that it should be focused on. WP CLI does a competent job with everything else.

**Comment by mnelson4** [comment]
thanks for the feedback @ThatGerber. I'm not terribly familiar with WP CLI, but I don't see how the Scaffold command does what I'm wanting. It seems like that generates scaffold code for plugins, themes, post-type-related-code etc. The WP CLI command `wp core install` seems the most related to what I'm wanting to do, but I don't see any option to install the unit-test-ready version of wp.
What I was hoping to do was use `vv` to create a wp site in vvv, but when choosing the branch of wp for the install, instead of `trunk` or `4.1` etc, I'd like to use the git repo at develop.git.wordpress.org (or the svn repo at develop.svn.wordpress.org really) instead of the repo from github.com/wordpress/wordpress. It would just be a convenient option for creating a development site that will be ready to run unit tests

**Comment by ThatGerber** [comment]
This is what provision.sh runs in VVV to set up WordPress Develop. https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/provision/provision.sh#L548

I think a better option than adding yet another flag/command would be to move a lot of this configuration into a yaml or directory-specific provision.sh file (or a combination of the two). That block from Provision.sh could be dumped into a provision-local.sh in the project root. Really, these are configurations that could/should be included in the project distribution. Anyone who works on this project or is cloning this repo would need to run that configuration through VVV-VV to work in a similar environment. Then you can manage the actual files commited to the repo and ignore anything that is installed automatically by the provisioning script or choose to commit them and lock in the file versions.

**Comment by mnelson4** [comment]
those lines from provision.sh are quite helpful: I see it just checks out the svn repo using `svn` and configures the site using `wp core config`

> I think a better option than adding yet another flag/command would be to move a lot of this configuration into a yaml or directory-specific provision.sh file (or a combination of the two)

And I agree I think having a configuration file, instead of having tons of command line options, would be good, especially if you're using this tool frequently. It might be nice to have a command line option to use a specific configuration file, that way folks who want to just use the classic command-line interface can, whereas those who want to edit a configuration file can do that also.

Anyways, I got what I needed working by cloning git://develop.git.wordpress.org/  into the site's folder created by `vv` (eg using `vv create` created a site called "mysite" which created a folder {vvv_root}/www/mysite and that's where I cloned the repo to), had to reconfigure the wp-config.php and the nginx server and restart it all, but after that it worked fine.
Maybe this is a rare use case (ie I'm the only person who ever wants to use this tool to setup a site that's ready to run unit tests)? If so I'm happy to just close this ticket. 
@ThatGerber is having an option in `vv create` to create a unit-testing-ready wp install something you'd also think good? Or is this just feature-creep and you'd really rather keep it out?

**Comment by bradp** [comment]
This is something I wouldn't mind supporting in `vv`. I just added the ability to clone down trunk for the WP install, and keep it up to date on every provision. Pulling down this version of WordPress can be added for sure.

As for the conversations about scope creep and default settings, I think those would be relevant for another conversation.

@mnelson4 I do think this is something I'd like to implement.

**Comment by bradp** [comment]
Closing this to track in the 2.0 release issue: https://github.com/bradp/vv/issues/161

**Comment by mnelson4** [comment]
cool!
