### ISSUE TITLE
vv delete or remove doesn't deletes the database associated with the site

### ISSUE THREAD

**Issue by mandooox** [bradp/vv#149]
After delete the site everything removed but database still founded which the deleting a site should have this option : 
> Deletes the database associated with the site 

screenshots : 
http://jmp.sh/Gag1Wbt
http://jmp.sh/3dhDntK

====
Mac os x Yosemite 10.10.3
vagrant version: 1.7.4
VVV stable version
vv version 1.8.0
VVV Dashboard Version: 0.0.5

**Comment by bradp** [comment]
This is due to VVV's database backups with the vagrant-triggers plugin. This has been fixed in 1.9, which will release soon.
