### ISSUE TITLE
vv create --locale is broken

### ISSUE THREAD

**Issue by minthemiddle** [bradp/vv#151]
The language/local option does not work any longer:

```
 vv create --locale fr_FR
[Error] Unknown option --locale
```

Running with most recent vv via git clone.
Mac OSX 10.11, fish, no other problems with vv.

**Comment by bradp** [comment]
This functionality is available in 1.9. Right now only 1.8.0 is available with brew, but the README talks about 1.9.0. I'll be releasing 1.9.0 shortly, I'm just doing final testing at the moment.
