### ISSUE TITLE
Moving VVV install breaks nginx config

### ISSUE THREAD

**Issue by zanetaylor** [bradp/vv#153]
I moved my VVV installation, and `vv create` began prompting me for my VVV path each time (because it had already set it in `~/.vv-config` and wasn't resetting it). Even when entering the correct VVV path at the prompt, `vv` didn't create the new site's .conf file in nginx-config. Manually updating the `.vv-config` file resolved the problem.

**Comment by bradp** [comment]
Closing this to track in the 2.0 release issue: https://github.com/bradp/vv/issues/161
