### ISSUE TITLE
Tab Completions doesn't work as described in Readme.md

### ISSUE THREAD

**Issue by pixolin** [bradp/vv#154]
Installed `vv`using Homebrew and added `source $( echo $(which vv)-completions)`to my `.zshrc`, which returns an error on opening a new shell: "/Users/pixolin/.zshrc:source:86: no such file or directory: /usr/local/bin/vv-completions".

I checked folder `/usr/local/bin/` which shows `vv`, but doesn't have any file `vv-completions`. Neither does the directory `/usr/local/Cellar/vv/1.8.0/bin` which seems to store the original files.

Is it possible, the changes haven't been "transferred" to Homebrew yet?

**Comment by bradp** [comment]
You are correct, right now only 1.8.0 is available with brew, but the README talks about 1.9.0. 1.9.0 should be releasing shortly, I'm just doing final testing at the moment.

**Comment by almone** [comment]
Today 1.9.3 is available with brew, nevertheless I also have the issue with . zshrc  as @pixolin described.

**Comment by bradp** [comment]
This looks like an issue with the Brew install. Just pushed an update to the formula that should fix it.

**Comment by almone** [comment]
@bradp thank you for the quick response! Everything is ok now.
