### ISSUE TITLE
How to create a new site without backing up current sites

### ISSUE THREAD

**Issue by DanielJLewis** [bradp/vv#156]
I have some large databases, so every time I run vv create, it re-backs up my databases. That takes a long time because of one of the big databases.

Any chance of offering a "--skip-backup" switch?

**Comment by bradp** [comment]
The backups are from the vagrant-triggers plugin, and there isn't a good way to avoid that, as creating sites requires a vagrant halt and a vagrant provision.

There are plans for a way to shortcut needing to reprovision, but until that gets added, there isn't a way around this.
