### ISSUE TITLE
vv -delete Database backup not removed

### ISSUE THREAD

**Issue by neilgee** [bradp/vv#163]
vv 1.9.0 with vagrant-triggers

When using **vv -delete** the backup database is not removed from _database/backups_ and subsequently restored on **vagrant up**

**Comment by bradp** [comment]
Can you paste the contents of `vv --debug-vv`?

**Comment by bradp** [comment]
Actually, just fixed it in beb36e620d43

Looks like 1.9.1 is going out early!

**Comment by neilgee** [comment]
Ok it's removing from the backups now - however the **live** database is still present, it's not being removed.
```
vv version 1.9.1

vv: /Users/neilg/vagrant-wordpress/vv/vv

vvv path: 	 /Users/neilg/dev
home: /Users/neilg

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/local/php5/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/bin/vagrant
```

**Comment by bradp** [comment]
It seems to be deleting just fine for me, try disabling the vagrant triggers plugin.

**Comment by neilgee** [comment]
Yes, so with _vagrant-triggers_ enabled and doing a vv --delete, _vagrant-triggers_ backs up the db to database/backups and then vv deletes it from their which is expected. But the live db is not removed eventhough the output confirms that it is.

```
Password:
Removing directory sample...  
Done
Removing nginx config file sample.conf...  
Done
Removing the database creation commands from init-custom.sql...  
Done
Removing database 
Done
Removing database backup 
Done
Removing any set up deployments.  
Done
[Success]
```
I also tried with _vagrant-triggers_ uninstalled but still the live database is present after doing the vv --delete process.

**Comment by mandooox** [comment]
@neilgee this what happened with me too, the contents of vv --debug-vv 
```
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path: 	 /Users/Mandooox/projects/wordpress
home: /Users/Mandooox

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
```
+ after vv delete as you notes vagrant will be [ halt + provision ] so after removing the site vagrant take more time to back live again

whatever really thank you for this stuff and the coming new features.

**Comment by meitar** [comment]
There's a PR open that fixes this: #237, though it references issue #210.

**Comment by meitar** [comment]
FWIW, the issue here is that (at least) the (latest) VVV MySQL config keeps database files in the guest's `/var/lib/mysql` directory, but this is not mapped to the host with a shared ("synced") folder. When `vv` brings the VVV guest down, there's no way to access the `/var/lib/mysql` database files, so the `rm -rf` of them can't work (and even if it could, that's not the cleanest way of deleting the DB files anyway).

The PR linked above runs a `vagrant ssh --command "mysql -u root -e 'DROP DATABASE $site;'" command from the host when Vagrant is running, thus dropping the DB correctly every time.

**Comment by bradp** [comment]
Should be fixed from https://github.com/bradp/vv/pull/237
