### ISSUE TITLE
Empty Site Creation no htdocs folder

### ISSUE THREAD

**Issue by neilgee** [bradp/vv#164]
vv 1.9.1

Referencing - https://github.com/bradp/vv/issues/141

Ran **vv --create --blank-with-db** but does **not** create __htdocs__ directory, does create:
* vvv-hosts
* vvv-init.sh

**Comment by bradp** [comment]
Confirmed bug. Fixed in e6039707824cd680625d536d3ae6608014f01bd9. 

Just tagged and released 1.9.2.

**Comment by neilgee** [comment]
Yes working Ok now
