### ISSUE TITLE
[Error] Path specified is not a VVV root directory. Where is VVV installed? VVV install directory:

### ISSUE THREAD

**Issue by danielwebguy** [bradp/vv#168]
Hi,
Its been 2 days that I am trying to install it.

screen shot of folders:
![image](https://cloud.githubusercontent.com/assets/15003148/10392068/704d9700-6e8c-11e5-8886-096409d9d04f.png)

Here is my Git Bash screenshot:
![image](https://cloud.githubusercontent.com/assets/15003148/10392091/9dba4062-6e8c-11e5-8708-4ae0eac9e81f.png)

vv-config file
![image](https://cloud.githubusercontent.com/assets/15003148/10392103/b6c276ba-6e8c-11e5-8fe1-2e0525eac25d.png)

please advise is possible 
Thanks
Daniel

**Comment by phatsk** [comment]
Hi @danielwebguy - your `.vv-config` "path" should point the `vvv` folder, not the `www` folder, try:

```
{
    "path": "D:\localdev\vvv\"
}

**Comment by bradp** [comment]
@danielwebguy Gonna close this issue, @phatsk's advice should be exactly what you need.

Feel free to re-open if you still have issues.
