### ISSUE TITLE
Bedrock option doesn't seem to be working

### ISSUE THREAD

**Issue by aburi** [bradp/vv#170]
When running **vv create --bedrock**, I get a blank white page when I try to load the site after installation has completed. The folder structure looks correct, but just can't get the site to work. Any idea what I might be doing wrong here?

**Comment by bradp** [comment]
The Bedrock installation does not come with any themes or plugins out of the box, so you'll need to add those in before the site can load. See the [documentation](https://github.com/roots/bedrock) for any help.
