### ISSUE TITLE
Group of Hooks

### ISSUE THREAD

**Issue by nicholasio** [bradp/vv#171]
It would be great if we could define groups of hooks to be executed while executing vv commands.

Instead of just putting all the hooks inside the vv directory, I was thinking in creating subfolders like "project-name" and when running vv scripts we would pass the group we want to execute.

$ vv create --hooks=project-name

If no group was specified we can just look for hooks in the root of vv.

This could be a simple way of creating provisioning scripts specific for projects and share this scripts among the members of a team.

I can try to provide this functionality, I was just wondering what you guys think about this.

**Comment by bradp** [comment]
That's not a bad idea!

In the meantime, I'd suggest checkout of [VVV Provision Flipper](https://github.com/bradp/vvv-provision-flipper), as it will let you toggle different provisioning profiles. Might be helpful for now.

**Comment by nicholasio** [comment]
Thanks @bradp I'll take a look!
