### ISSUE TITLE
blueprint is not working

### ISSUE THREAD

**Issue by jorcons** [bradp/vv#172]
I have created my blueprint in VVV root directory vv-blueprints.json and create a site with flag  --blueprint blueprint-name but not works for me. Console shows:
==> default: /srv/www/mytest
==> default: PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
==> default: PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
==> default: Setting up blueprint visible-foundationPress...
==> default: Blueprint set up.
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added mytest.dev from /srv/www/mytest/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 367 seconds

**Comment by jorcons** [comment]
My vv-blueprints.json

{
  "visible-foundationPress": {
    "themes": [
      {
        "location": "https://user@bitbucket.org/team/visible-foundationpress.git",
        "activate": true
      }
    ],
    "plugins": [
      {
        "location": "https://github.com/wp-plugins/contact-form-7.git",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/really-simple-captcha.1.8.0.1.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/html-editor-syntax-highlighter.1.6.8.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/wordpress-importer.0.6.1.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
    ],
    "options": [
      "current_theme::Visible FoundationPress"
    ],
    "demo_content": [
      "link::https://bitbucket.org/snippets/comvisible/pLKp6/wp_base_content_xml"
    ],
    "defines": [
      "WP_CACHE::false"
    ]
  }
}

**Comment by bradp** [comment]
Two things that you can try. The first is try this in your Blueprints file:

Also make sure you're doing --blueprint visible-foundationPress

 ```
{
    "visible-foundationPress": {
        "themes": [
            {
                "location": "https://user@bitbucket.org/team/visible-foundationpress.git",
                "activate": true
            }
        ],
        "plugins": [
            {
                "location": "https://github.com/wp-plugins/contact-form-7.git",
                "version": null,
                "force": false,
                "activate": true,
                "activate_network": false
            },
            {
                "location": "https://downloads.wordpress.org/plugin/really-simple-captcha.1.8.0.1.zip",
                "version": null,
                "force": false,
                "activate": true,
                "activate_network": false
            },
            {
                "location": "https://downloads.wordpress.org/plugin/html-editor-syntax-highlighter.1.6.8.zip",
                "version": null,
                "force": false,
                "activate": true,
                "activate_network": false
            },
            {
                "location": "https://downloads.wordpress.org/plugin/wordpress-importer.0.6.1.zip",
                "version": null,
                "force": false,
                "activate": true,
                "activate_network": false
            }
        ],
        "options": [
            "current_theme::Visible FoundationPress"
        ],
        "demo_content": [
            "link::https://bitbucket.org/snippets/comvisible/pLKp6/wp_base_content_xml"
        ],
        "defines": [
            "WP_CACHE::false"
        ]
    }
}```

**Comment by jorcons** [comment]
Hi, yes I'm doing --blueprint visible-foundationPress.
Sorry, but I can't see the difference with my Blueprints file.

**Comment by jorcons** [comment]
ok, sorry I see that i have a semicolor in last plugins array item. I have removed and seems work. But with .git repos such as theme or plugins I have this error on console:
==> default: Setting up blueprint visible-foundationPress...
==> default: Installing themes...
==> default:   Installing https://jorcons@bitbucket.org/comvisible/visible-foundationpress.git --activate...
==> default: error: unknown option `activate'
==> default: usage: git clone [options] [--] <repo> [<dir>]

It seems that "activate": true, does not work with git repos. For .zip files works fine.

**Comment by bradp** [comment]
Try using the SSH git repo address instead of the https link and let me know if that works.

**Comment by jorcons** [comment]
Hi, with ssh also not works:
==> default: /srv/www/mytest
==> default: PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
==> default: PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
==> default: Setting up blueprint visible-foundationPress...
==> default: Installing themes...
==> default:   Installing ssh://git@bitbucket.org:team/visible-foundationpress.git --activate...
==> default: error: unknown option `activate'

**Comment by bradp** [comment]
What does your vvv-init.sh file look like for this site?

**Comment by jorcons** [comment]
This is my vvv-init.sh

if [ ! -d "./wp-admin" ]; then
	echo 'Installing WordPress (release version) in mytest/....'
	if [ ! -d "./." ]; then
		mkdir ./.
	fi
	cd ./.
	wp core download --locale=en_US --allow-root 
	wp core config --dbname="mytest" --dbuser=wp --dbpass=wp --dbhost="localhost" --dbprefix=wp_ --locale=en_US --allow-root
	wp core install --url=mytest.dev --title="mytest" --admin_user=user --admin_password=password --admin_email=jconstanti@comunicacionvisible.com --allow-root
	
	
  wp theme delete twentythirteen --allow-root; wp theme delete twentyfourteen --allow-root; wp theme delete twentyfifteen --allow-root; wp theme delete twentysixteen --allow-root; wp plugin delete hello --allow-root; wp plugin delete akismet --allow-root; git checkout HEAD .
  
	
	
	cd -
curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install visible-foundationPress . mytest mytest.dev && rm vv-blueprints.json
fi

**Comment by Drixled** [comment]
Hi, i have the same problem. I tried with the same json file you previously put brad but still does not work. This is my vvv-init.sh file:

```
if [ ! -d "htdocs/wp-admin" ]; then
	echo 'Installing WordPress (release version) in _test/htdocs...'
	if [ ! -d "./htdocs" ]; then
		mkdir ./htdocs
	fi
	cd ./htdocs
	wp core download --locale=en_US --allow-root 
	wp core config --dbname="_test" --dbuser=wp --dbpass=wp --dbhost="localhost" --dbprefix=wp_ --locale=en_US --allow-root --extra-php <<PHP
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', true);
define('SCRIPT_DEBUG', true);
define('JETPACK_DEV_DEBUG', true);
PHP
	wp core install --url=test.dev --title="_test" --admin_user=admin --admin_password=password --admin_email=admin@localhost.dev --allow-root
	
	
  
  
	
	
	cd -
curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install visible-foundationPress htdocs _test test.dev && rm vv-blueprints.json
fi
```

**Comment by bradp** [comment]
@jorcons @Drixled Can you do a 'vagrant ssh' and go to your site folder and run just the last command from vvv-init.sh in your terminal and send me the output? Just the line starting with 'curl -o vv-install'. I think the issue is something is not being passed in correctly, or its hitting an error somewhere in there.

**Comment by Drixled** [comment]
Forget it, my problem is that previously configured the config file in the .ssh folder for a remote connection to my host in Siteground, which caused vagrant could not connect via SSH. I just made a new test with a blueprint and everything works properly. Thanks!

**Comment by jorcons** [comment]
brad I run the command and this is the output:
vagrant@vvv:/srv/www/mytest$ curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install visible-foundationPress . mytest mytest$
PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
PHP Notice:  Undefined variable: arg in /srv/www/mytest/vv-install on line 218
Setting up blueprint visible-foundationPress...
PHP Warning:  file_get_contents(vv-blueprints.json): failed to open stream: No such file or directory in /srv/www/mytest/vv-install on line 9
Blueprint set up.

**Comment by bradp** [comment]
Try removing the site and recreating please.

**Comment by jorcons** [comment]
I remove and recreate some times and always the same. But the problem is only with the theme and the content. May be a issue with bitbucket repos?

**Comment by jorcons** [comment]
I have try with a github repo and the same problem.

**Comment by jorcons** [comment]
I think the problem is in vv-install script lines 112-117:
/**
	 * Set up the rest of the command for this installation depending
	 * on the type of installation we are going to do
	 */
	// Clone a git repository
	if ( false !== strpos( $target, '.git' ) ) {
		$command .= " && git clone $target";
		// Comenting this the repo downloads and have no error but is not activated automatically
                // if ( $wpcli_compat ) {
		// 	$command .= $wpcli_options;
		// }
	}

I think is concatenating --active in git clone command. If I comment this, script clone theme repo ok but logically not active it. I don't know how do the active with wp-cli for the theme.

**Comment by Mte90** [comment]
I've tried and not work, in `vv create` i've added the name of `vv-blueprints.json`, the file is copied in the site folder but not executed.

**Comment by Mte90** [comment]
https://github.com/bradp/vv/blob/vv-install/vv-install#L218
I think that there is an error, the correct is:
```main( $argv[1], $argv[2], $argv[3], $argv[4] );```

**Comment by bradp** [comment]
Updated.

**Comment by kriskhoury** [comment]
Has this been figured out?

This is what I have for my `vv-blueprints.json`:

```javascript
{
  "base": {
    "themes": [
      {
        "location": "https://user@bitbucket.org/username/my-theme.git",
        "activate": true
      }
    ],
    "plugins": [
      {
        "location": "https://downloads.wordpress.org/plugin/advanced-custom-fields.4.4.4.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/wordfence.6.0.22.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/better-wp-security.5.1.1.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/sucuri-scanner.1.7.16.zip",
        "version": null,
        "force": false,
        "activate": true,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/wordpress-seo.3.0.6.zip",
        "version": null,
        "force": false,
        "activate": false,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/admin-menu-editor.1.5.zip",
        "version": null,
        "force": false,
        "activate": false,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/wp-super-cache.1.4.6.zip",
        "version": null,
        "force": false,
        "activate": false,
        "activate_network": false
      },
      {
        "location": "https://downloads.wordpress.org/plugin/iwp-client.zip",
        "version": null,
        "force": false,
        "activate": false,
        "activate_network": false
      }
    ],
    "defines": [
      "WP_CACHE::false"
    ]
  }
}
```

The following is the error when I use the `git` path:
```text
==> default: error: unknown option `activate'
==> default: usage: git clone [options] [--] <repo> [<dir>]
```

The following is the error when I use the `zip` path:
```text
==> default: Warning: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
```

Any ideas?
