### ISSUE TITLE
-skel doesn't install WP or the latest version

### ISSUE THREAD

**Issue by rezzz-dev** [bradp/vv#173]
I'm loving ability to create a new site using the Skeleton structure, however I've noticed that it does not download the latest WordPress version (using 4.2.2).  Also that it doesn't install WP either.  When I goto the local URL, I get prompted to install.  

Am I missing something on these two items, or is that meant to be?

**Comment by rezzz-dev** [comment]
Also doesn't seem to remove the default themes and plugins as well.

**Comment by bradp** [comment]
The WP skeleton install doesn't really inherit all the flags, as its a different install method. For WP not getting installed, you'll have to do a 'git submodule init; git submodule update'.

Basically, the --skel install gets you WP skeleton straight from the git repo, and thats about it.

If there is enough interest, I can add more functionality around it.

**Comment by rezzz-dev** [comment]
Ah gotcha -- no worries then.  Thought maybe I was just missing some things.
