### ISSUE TITLE
Improve the debug parameters

### ISSUE THREAD

**Issue by Mte90** [bradp/vv#174]
Source: https://webdevstudios.com/2015/10/15/debugging-wordpress-tips-snippets/

```
define( 'WP_DEBUG', true );
define ('JETPACK_DEV_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'SCRIPT_DEBUG', true );
if ( defined( 'DOING_AJAX' ) && DOING_AJAX || defined( 'DOING_CRON' ) && DOING_CRON ) {
    define( 'WP_DEBUG_DISPLAY', false );
    @ini_set( 'display_errors', 0 );
} else {
    define( 'WP_DEBUG_DISPLAY', true );
}
```
I think that code is not bad because disable the error reporting in the ajax/cron request that are difficult to track, is better use the debug.log file generated from vvv in wp-content folder.

**Comment by bradp** [comment]
Added in https://github.com/bradp/vv/commit/f27333ffc11178a5bc9fe03ad6a087dc889621ca, for the 2.0 release.
