### ISSUE TITLE
Command to update all the sites

### ISSUE THREAD

**Issue by Mte90** [bradp/vv#175]
If I want to update all the wordpress installation (created with vv) with a command is not possible.
Maybe will be a cool feature without enable the auto updating on the wordpress installation.

**Comment by Mte90** [comment]
any news?

**Comment by bradp** [comment]
Hey, they would be neat!

**Comment by bradp** [comment]
I'm not sure the best way to accomplish this though, as you can set up non-WP sites, and after set up nothing about that is tracked. Might be better as a WP CLI command or a server command.
