### ISSUE TITLE
Better Linux & non-Homebrew Mac install instructions

### ISSUE THREAD

**Issue by bradp** [bradp/vv#182]

**Comment by thisislawatts** [comment]
Hey @bradp,
Installing via homebrew is only loading version 1.7.2, do you know of a way to force loading version 1.9.3?

**Comment by numediaweb** [comment]
For Linux;
- [ ] Clone the repository somewhere into your system (personally I clone it inside the vvv folder) 
```git clone https://github.com/bradp/vv.git ```
- [ ]  Get the newly cloned vv folder path and copy the path
```bach
cd vv
pwd
```
- [ ]  Add the copied path to your system path; for example, I put the vv into `/media/abdel/Works/apps/wp/vv` so I use:
```bach
PATH=$PATH:/media/abdel/Works/apps/wp/vv
```
