### ISSUE TITLE
Per-site blueprint files

### ISSUE THREAD

**Issue by stevegrunwell** [bradp/vv#184]
If you're looking for things to consider with Blueprints (especially in version 2.0, as mentioned in #161), the ability to specify a vv-blueprints.json file would be extremely helpful for development teams.

Imagine being able to pass a blueprint file to a new engineer and let them automatically provision not only a WordPress instance but the necessary theme(s), plugins, and content.

**Comment by meitar** [comment]
This is something I need and am interested in working on. I would also like to see the blueprint file support multisite parameters, if it doesn't yet? (I'm new to `vv` and didn't see if that was possible, please correct me if I'm wrong.)

**Comment by meitar** [comment]
Have a look at #238 and #239 for pull requests that add multisite support to `vv-blueprints.json`.

**Comment by bradp** [comment]
Should be good now, @meitar is a rockstar.
