### ISSUE TITLE
Add ability to import sql.gz exports from sequel pro

### ISSUE THREAD

**Issue by bradp** [bradp/vv#186]
Also lets make the db import process more clear

**Comment by zanematthew** [comment]
I just tried this, and the db import did not work for me. I tried the following when prompted.

`/path/to/my/file/db.sql`

The `db.sql` file was a db dump from a WordPress website.

**Comment by bradp** [comment]
The db needs to be a full path, not relative and no expansion takes place.

**Comment by zanematthew** [comment]
Glad this is closed. Thanks for a great product.
