### ISSUE TITLE
Check for local `.vv-config` to allow multiple VVV installs

### ISSUE THREAD

**Issue by schlessera** [bradp/vv#187]
I would love for VV to check if the current path contains a `.vv-config` and then load that instead.

I want to have a few separate VVV installs. So, the easiest to way to allow this would be to cd into the correct VVV root and launch VV from there. Each VVV root could then have it's own `.vv-config`.

**Comment by bradp** [comment]
This is in 2.0 now, if you want to re-submit https://github.com/bradp/vv/pull/188/ without the version number bump, I can merge into master so we don't need to wait for 2.0.

**Comment by schlessera** [comment]
Done and thanks!
