### ISSUE TITLE
Delete vs Remove vs Teardown

### ISSUE THREAD

**Issue by jb510** [bradp/vv#190]
These seem to be aliases of each other:
https://github.com/bradp/vv/blob/master/vv#L1553

The readme.md seems to use delete:
https://github.com/bradp/vv#usage
https://github.com/bradp/vv#site-deletion
Elsewhere, it uses remove.

I'd like to suggest clarifying this and if there are any differences?  I'm not sure which is the most correct or I'd happily update the readme.

**Comment by pidgypost** [comment]
it seems like they do the same thing but one is asking for the site name and one is asking for the url name.

if you have the following...

vv create -d testURL -n testName

vv delete testName  <-- delete works with dir name
vv remove testURL   <-- remove works with domain

If nothing else its a little redundant and leads to thoughts of "did it delete or remove everything? Do i need to run both?"

Further clarification would be great!
