### ISSUE TITLE
Can't skip wizard

### ISSUE THREAD

**Issue by jordanmaslyn** [bradp/vv#191]
I am trying to automate site creation as part of my workflow. I am using the following command:

```sh
vv create --defaults --path /Users/myprofile/Sites/vagrant-local --force-path --name demosite --domain demosite.dev --debug --username COLABADMIN --password PASSWORD --email fake@email.com --remove-defaults
```

According to my understanding of docs, this should create the site without any interaction needed on my part, however I still get a popup saying

```
Automagically found
Is this where vv is installed? (Y/n):
```

Is there a way around this? Thanks for your awesome tool!

**Comment by bradp** [comment]
The easiest way is to run the command like this:

` yes | vv create --defaults --path /Users/myprofile/Sites/vagrant-local --force-path --name demosite --domain demosite.dev --debug --username COLABADMIN --password PASSWORD --email fake@email.com --remove-defaults`

The `yes |` will answer 'yes' to all prompts.

**Comment by jordanmaslyn** [comment]
Awesome, thanks... unfortunately with that I get an endless stream of errors reading:

```
[Error] Path specified is not a VVV root directory. Where is VVV installed?
```

I know I am giving it the right directory "/Users/jordanmaslyn/Sites/vagrant-local". Any ideas?

If I don't pipe the "yes" in, it says it automagically found it, asks me if that's where VV is installed (I say Y), and then asks me to provide a VVV install directory (despite automagically find it and me providing the path to it explicitly in the command).

**Comment by bradp** [comment]
Two things you can try to potentially solve that.

1) Does the Vagrantfile exist at "/Users/jordanmaslyn/Sites/vagrant-local" or is it perhaps another level deeper?
2) Does the file `~/.vv-config` exist, and if so, what does it contain?

Also, what does the output of `vv --debug-vv` give you?

**Comment by jordanmaslyn** [comment]
1) Yes there is a vagrant file within vagrant-local.
2) ~/.vv-config does exist and contains
```
{
    "path": "/Users/jordanmaslyn/Sites/vagrant-local"
}
```
and vv --debug-vv gives me:
```
----------
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path:      /Users/jordanmaslyn/Sites/vagrant-local
home: /Users/jordanmaslyn

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/local/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
----------
```
