### ISSUE TITLE
VV not creating database?

### ISSUE THREAD

**Issue by colinswinney** [bradp/vv#192]
I've been using VV, Vagrant, et al for a few months now and have successfully created/destroyed etc in the past.  Last night I went to vv create and it did everything, except it didn't create a database and viewing phpMyAdmin at vvv.dev confirms this.   

I've done vv --debug-v and get this:
------------------------------------------------
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path: 	 /Users/colinswinney/Desktop/vvv
home: /Users/colinswinney

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/bin/vagrant

------------------------------------------------------------

My VVV path is incorrect (I'd love to correct that if you know how), but VV just always asks for the root and I simply type the path without issue.  Any ideas why DB's aren't being created?  I've done vv --update, is there an uninstall/reinstall command or option?

**Comment by colinjswinney** [comment]
Well, after updating VV, Vagrant, and running "vagrant box update", databases are being correctly added on vv create.  However, the new site times out and the server cant be found.  I can access and view all previously created sites at local.mysite.dev for example, but the new ones I created don't load.  

This stuff can be so frustrating... perhaps this is no longer a VV issue, but any ideas why this isn't working?  My wp-config file looks normal, the phpMyAdmin tables and users look normal... I'm at a loss as to what would be different.

**Comment by bradp** [comment]
If the path is incorrect, you'll need to update ~/.vv-config with the correct path.

That is most likely the cause of your issues.
