### ISSUE TITLE
VV Can't Locate VVV Install Directory

### ISSUE THREAD

**Issue by milosvujnovic** [bradp/vv#193]
Hi guys,

on Windows 8.1 -- I'm having issues setting up VV (I've followed all instructions including setting up PATH).

My VVV is installed at "C:\dev\vagrant-local"
Current setup VVV + Git for Windows + Posh-Git.

After doing Git Bash in the VV directory and entering the path above, I get "[Error] Path specified is not a VVV root directory. Where is VVV installed?".

I've tried entering jut "/dev/vagrant-local" and similar but no luck.
Not sure what am I doing wrong - could you please suggest what how can I fix this?

Thanks so much!

**Comment by eriktdesign** [comment]
Try /c/dev/vagrant-local

**Comment by milosvujnovic** [comment]
Thanks so much Erik, that worked!
