### ISSUE TITLE
Access denied for user 'wp'@'localhost' on new database

### ISSUE THREAD

**Issue by montchr** [bradp/vv#198]
I just ran `vv create` to set up a new site, and when I `vagrant ssh` to import a SQL file with `wp db import` I get this message:

```
ERROR 1044 (42000): Access denied for user 'wp'@'localhost' to database 'new-database'
```

Shouldn't the `wp` user be given access during the install process?

**Comment by jb510** [comment]
If you check in phpmyadmin has the database been created?

Have a look at the vvv-init.sh script in the root of that project and see if that looks  correct:
https://cloudup.com/cZwy-SBWNMT

That script gets run when VVV gets provisioned with `vagrant up --provision`

**Comment by montchr** [comment]
> If you check in phpmyadmin has the database been created?

It was not created. I deleted the site folder and re-ran the `vv create` command, this time using an absolute path to tell it where the VVV directory is. Success. Seems that every time I run `vv` it can't find the config file and forgets where VVV is installed. But that's a separate issue.
