### ISSUE TITLE
VBoxManage.exe not found

### ISSUE THREAD

**Issue by eriktdesign** [bradp/vv#199]
On my install (Win10, latest VirtualBox and Vagrant), when performing `vv create`, an error occurs. Seems that when vv checks if the vagrant is up, `VBoxManage.exe` cannot be found. Looks like it can be fixed by adding (for me) `C:\Program Files\Oracle\VirtualBox` to the `path` -- perhaps this needs to be added to the instructions?

**Comment by jb510** [comment]
Thanks for the report. I was afraid this could cause problems with windows.  

See #194

**Comment by eriktdesign** [comment]
Actually, that didn't seem to fix it. Now it just fails silently. I have to manually `vv vagrant halt` before adding a site or it gets screwy.

**Comment by jb510** [comment]
Hoping @bradp had an idea on how to handle it (been a long time since I delt with Windows).  

Until we fix it you can comment out that check in vv. Running vagrant halt always is the old behavior, it's harmless, it's just slow.

**Comment by jb510** [comment]
Comment out lines 1108-1110 and 1112-1114.  Just leave the vagrant halt command.  Sorry on a phone or I'd put in a patch.

**Comment by bradp** [comment]
Yeah, we'll most likely need to add some checks for Win/*nix and behave differently.

We also may need to do a check for Vbox / Parallels and switch based on that.

@jb510 Our other option is switching to where we ping and see if we get a correct response from a local site to determine whether or not to 'vagrant halt'.  I can get that implemented tomorrow.

**Comment by bradp** [comment]
Just pushed an update in 5e64b56cc2ab & 818d21d305089859dd82b25f7739d723ad14d9e0
