### ISSUE TITLE
Install WordPress at project root, not in htdocs.

### ISSUE THREAD

**Issue by josephfusco** [bradp/vv#206]
Going over other issues, I am trying to find a flag or someway to install WordPress to match the structure of existing VVV default sites. I noticed `--webroot` but this seems to only change the name of the htdocs directory.

Right now WordPress is being installed in here:
```
www/project/htdocs/
```

Goal:
```
www/project/
```

Thanks!

**Comment by GaryJones** [comment]
Could you do something like `--webroot=""`?

**Comment by josephfusco** [comment]
Unfortunately passing an empty string `--webroot ''` doesn't work.
```
[Error] --webroot expected an argument
```

**Comment by GaryJones** [comment]
Maybe `--webroot="./"`? Just guessing.

**Comment by bradp** [comment]
`--webroot .` should accomplish this.
