### ISSUE TITLE
For some reason it is not reloading correctly for me

### ISSUE THREAD

**Issue by fclaussen** [bradp/vv#207]
System: Windows 10
Bash is git bash with admin permission

Problem: When I run vv create it asks me a few questions, fine. Then it says what is going to happen and when I say yes it runs just a few lines, like 10 or so and it's done.

When I try to access the new site it does not work. If I run vagrant reload --provision after this It works.

Any idea what could be the problem?

I tested on a different pc and it works as expected using the same version.

**Comment by bradp** [comment]
Please [review the guidelines](https://github.com/bradp/vv/blob/master/CONTRIBUTING.md) for contributing to this repository and follow the steps when posting an issue, thank you.
