### ISSUE TITLE
Plugins With Licenses

### ISSUE THREAD

**Issue by LukePettway** [bradp/vv#208]
I did a little searching and didn't seem to come across anything but is it possible to install plugins and their associated product keys? I use ACF a lot and it would be cool to have an option to point to a keyfile or post the key in my blueprint.

**Comment by eriktdesign** [comment]
I was thinking about this with Gravity Forms. For Gravity, you should be able to do the following: 

    "defines": [
      "GF_LICENSE_KEY::xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ]

If you can find what option that ACF is stashing the key in, you should be able to assign it.

**Comment by bradp** [comment]
The blueprints will allow you to do a wp-config define() and a database option.

That should be able to accomplish it. Otherwise, this'll be too plugin-specific to support.

**Comment by jb510** [comment]
+1 blueprints already handles this.  You can customize your default WP-config file to include those defines.

**Comment by LukePettway** [comment]
Thanks everyone, I'm still fairly new to using VV so I'll go and check out using the config file for the defines.
