### ISSUE TITLE
create multisite with bedrock 

### ISSUE THREAD

**Issue by sandrodz** [bradp/vv#209]
Creating multisite with bedrock causes following error:

```Constant MULTISITE already defined```

it seems the problem is that vv adds constants to wp-config which is incorrect (in case of bedrock). these constants should be added to `bedrock/config/application.php`

**Comment by reverbsoul** [comment]
Ran in to the same issue, cut the multisite lines out of wp-config and moved them to the bottom of my application.php file and it works perfectly. Not sure if there is a way to create the site with these settings from vv, but that would be nice. Although I really only need to do any of this once (unless I'm testing).

**Comment by bradp** [comment]
I don't want to build this much support in for bedrock, as we're just using WP CLI to set up sites, and this requires a lot of edge case checking. If this process only needs to be manually done once, that is acceptable to me.

If someone wants to PR a fix for this, I'd be happy to merge in though.
