### ISSUE TITLE
bedrock init script issues

### ISSUE THREAD

**Issue by sandrodz** [bradp/vv#211]
I've noticed bugs wile creating bedrock project.

1 - inside vvv-init `mkdir` and later `cd` is not needed at all! First of all, because these directories cannot be created or cded into before composer runs, and second composer creates all the necessary dirs anyways. 
``` 
       if [ ! -d "./htdocs/web" ]; then
		mkdir ./htdocs/web
	fi
	cd ./htdocs/web
	composer create-project roots/bedrock htdocs
```    
2 - wp_cli doesn't work because path inside wp-cli.yml is incorrectly set, it needs to be `path: htdocs/web/wp` instead of `path: htdocs/web`

I've tried to look into vv source, and it seems `web_root` for bedrock should be set to `htdocs/web/wp` this fixes second issue but doesn't take care of first issue.

I don't feel familiar enough to the bash scripting or your code to push PR. Sorry.

**Comment by perssonmattias91** [comment]
+1 on bedrock init script issues. Getting 403 forbidden after setting up a new site with bedrock and cloning an empty BitBucket repo. This seems to add both another htdocs folder inside [project]/htdocs/web/, but also clone the repo into a wp-content folder on the same level.

Setting up a bedrock site without cloning a git repositorie works fine for me.
