### ISSUE TITLE
Multiple site creation

### ISSUE THREAD

**Issue by Drixled** [bradp/vv#212]
Hi, is there any way to create multiple sites in a vv command? 
Thanks for your time.

**Comment by meitar** [comment]
I don't think so, unless you're talking about subsites in a multi-site network, in which case have a look at #238 and #239.

**Comment by bradp** [comment]
There is not a default way for this. You can feed all needed flags to vv create and run `yes | vv create --name firstsite --domain firstsite.dev <etc> && yes | vv create --name secondsite --domain secondsite.dev <etc>`.
