### ISSUE TITLE
Wizard path issues continued

### ISSUE THREAD

**Issue by diddledan** [bradp/vv#213]
References: #161, #177, #179.

The prompt to confirm the path is case-sensitive, so typing "y" will not work. Nor does the check allow pressing enter to confirm the default choice. (In standard parlance, an upper-case prompt in the form of "Y/n" indicates that the upper-case character is the default when no text is entered. Likewise "y/N" would indicate that the "n" would be default.)

**Comment by bradp** [comment]
This is not the case, from my testing and the code. https://github.com/bradp/vv/blob/master/vv#L521

**Comment by diddledan** [comment]
While the code is correct now, I'd like to point out that the code you cite was changed 35 minutes ago fixing this issue
