### ISSUE TITLE
.vv-config in local directory not overwriting home

### ISSUE THREAD

**Issue by dgautsch** [bradp/vv#218]
Hello,

When I create a `.vv-config` file in my project folder. `vv list` will still output the contents of the home path. It doesn't seem to be overridden by my local installation.

Am I configuring things wrong perhaps?

EDIT:
Contents of my local .vv-config

```{
	"path": "./vvv"
}```

vv version is 1.9.3


EDIT 2:

Ok just checked my local file and it seems even though i have version 1.9.3 the logic to test for the local config file is missing.

`test -f "$HOME"/.vv-config && got_config="true"` exits

but not

`test -f ./.vv-config && vv_config="./.vv-config"`

I will try reinstalling vv with homebrew and see if this resolves the issue.

EDIT 3:

Just reinstalled with homebrew from this URL https://github.com/bradp/vv/archive/1.9.3.tar.gz

That tar does not contain the logic necessary for local config files. 

EDIT 4:

This was fixed here https://github.com/bradp/vv/commit/c959c738a9516c1ee05fdfe50eb28d3c601876e1

Until this is tagged for homebrew, you'll have to update manually.

**Comment by yumyo** [comment]
Thank you so much for the detailed report. It is safe to manually update a brew installed vv or the formula needs to be removed before a full manual vv install?

**Comment by dgautsch** [comment]
Hi yumyo, I believe if you manually override the files `brew doctor` might report unbrewed packages in your bin folder. I don't think it will break anything but just be prepared to have it overwritten when the next release does make it out.

**Comment by yumyo** [comment]
ok crystal clear, thank you @dgautsch

**Comment by bradp** [comment]
If there are futher
