### ISSUE TITLE
Include language selection in creation

### ISSUE THREAD

**Issue by hlashbrooke** [bradp/vv#219]
It would be cool if you could specify the language of your WordPress install as part of the `vv create` command - that way you wouldn't have to open up the dashboard and change it each time if there was a specific language that you always use for WordPress. Easiest way to achieve this would probably be to have an option on create to specify the language code and then, if it is available for core, the relevant language pack would be downloaded.

**Comment by bradp** [comment]
This is possible, with the `--language` or `--locale` flags during creation. See https://github.com/bradp/vv#options-for-site-creation at the bottom for info.
