### ISSUE TITLE
Can't update to latest version

### ISSUE THREAD

**Issue by joelworsham** [bradp/vv#222]
I get this:

```
Your version of vv ( 1.8.0 )  does not match the current Github version ( 1.9.3 ). Please update with vv --update
vv version 1.8.0
```

I attempt to update using `vv --update`. I get this output:

```
Your version of vv ( 1.8.0 )  does not match the current Github version ( 1.9.3 ). Please update with vv --update
Updating vv via Brew...
Warning: Skipping highlight: most recent version 3.23 not installed
Warning: Skipping libgpg-error: most recent version 1.20_1 not installed
Warning: Skipping libksba: most recent version 1.3.3 not installed
Warning: Skipping lua: most recent version 5.2.4_1 not installed
Warning: Skipping node: most recent version 4.1.1 not installed
Warning: Skipping openssl: most recent version 1.0.2d_1 not installed
==> Reinstalling bradp/vv/vv
==> Downloading https://github.com/bradp/vv/archive/1.8.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/vv-1.8.0.tar.gz
🍺  /usr/local/Cellar/vv/1.8.0: 5 files, 84K, built in 2 seconds
```

But , as you can see, 1.8.0 is the latest in brew. I tried to update hoping it might fix my other issue #221

**Comment by bradp** [comment]
You  may need to run `vv --force-update``, as mentioned [here](https://github.com/bradp/vv#updating).

**Comment by joelworsham** [comment]
Thanks Brad, though I'm getting this output when trying that:
```
Forcing boostrapped update...
cat: /Users/joelworsham/vv-/vv: No such file or directory
/usr/local/bin/vv: line 217: /usr/local/bin/vv: Permission denied
[Success] vv has been updated to the latest version. Thanks!
```

It says success, but I don't believe it's working. Also, the output from `vv --version` is still `v version 1.8.0`

**Comment by joelworsham** [comment]
Update (no pun intended): I was able to get it to work by using this part from the readme:

>Second, if that does not work you can safely uninstall Variable VV and re-install it via homebrew, you can do this with these commands: brew remove vv then brew untap bradp/vv and finally, run the install command brew install bradp/vv/vvas mentioned above. You will not lose any settings or sites.

Thanks again for the help.
