### ISSUE TITLE
vv create -> Connection Timed Out 

### ISSUE THREAD

**Issue by PsySolix** [bradp/vv#228]
**VV version:** version 1.9.3
**VV debug:**
vv: /usr/local/bin/vv

vvv path: 	 /Users/admin/Documents/personal/vagrant/vagrant-local 
home: /Users/admin

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant

Hi everyone!

I hope you guys can help me with the problem I'm facing.. 

I installed VVV, I checked the wordpress builds that came with it. 
All the sites in the screenshot I can connect to without a problem after using `vagrant up`.
![image](https://cloud.githubusercontent.com/assets/6713256/13120980/8cf3e838-d5b0-11e5-9026-80e830354e6b.png)

**The Problem**
After using vv create (fopaz.dev) and entering all the details about the site -> everything go's smooth, no errors, success messages in terminal. Then in vvv dashboard I purge the hostfile to list the new fopaz.dev site. 
However I can't connect to fopaz.dev. **Connection timed out (chrome message)**

_The folder structure after installation of the vv create_
![image](https://cloud.githubusercontent.com/assets/6713256/13121573/08de0e7c-d5b3-11e5-90d9-08b42ca68621.png)

**Can someone help me with this issue, I would love to have this workflow going**

Thanks in advance!

**Comment by bradp** [comment]
What do you mean by "vvv dashboard I purge the hostfile"?

**Comment by PsySolix** [comment]
Ah sorry for not explaining more:I use the https://github.com/leogopal/VVV-Dashboard.
Below are some screenshots. 

Thx for immediate response Ö

![image](https://cloud.githubusercontent.com/assets/6713256/13121726/d9aaad58-d5b3-11e5-98b8-333e39d4f0df.png)

![image](https://cloud.githubusercontent.com/assets/6713256/13121718/ceb2fea0-d5b3-11e5-94f9-a71f5f6b2b60.png)

**Comment by PsySolix** [comment]
Do you have an idea? Or maybe point me in the right direction? :dart: :8ball:

**Comment by PsySolix** [comment]
Still no more? Greets!

**Comment by PsySolix** [comment]
**FIXED**

I figured out what the problem was.. God I feel so nooby.
the etc/host file didnt get updated for the new sites..

Putting it in with the vagrant ip fixed it! 

Sorry for taking up your time, loving this workflow <3

**Comment by jb510** [comment]
Glad you got it sorted.

FWIW, it sounds like you need to install vagrant-ghost or vagrant-hostsupdater

After a `vv create` you need to reprovision vagrant so it picks up the settings in vvv-hosts and populates those into /etc/hosts.  

FWIW, I haven't used Leo's dashboard in a while, but I don't recall there being a "purge hosts file" option and your screenshot looks significantly different that I remember that dashboard looking. Regardless, I have no idea what "purge hosts file" would actually do, but it sounds like it'd remove the settings in the hosts file, not update them, that'll obviously break domain name resolution, not fix it.
