### ISSUE TITLE
Deployment progress?

### ISSUE THREAD

**Issue by rootion** [bradp/vv#229]
Is there a way to see the deployment progress and log (something perhaps as --verbose?)?
I've been attempting to push a deployment I created and it's taking hours. I see the ftp folder remains untouched. I would like to know if there is something going on or not.

Thanks

**Comment by bradp** [comment]
The deployment just runs through Vagrant Push. I'd recommend running the vagrant push command directly. See the docs [here](https://www.vagrantup.com/docs/push/).
