### ISSUE TITLE
VV does not remember I ran it

### ISSUE THREAD

**Issue by thatryan** [bradp/vv#230]
Each time I type `vv` to add or delete a site, it acts as though I have never ran it before. Unsure why as it had worked before.

Running v. 1.9.3. Only thing new is I updated VVV the other day.

Screenshot is me trying to delete a site that I created with VV a few days ago...

![2016-02-21 at 9 23 pm](https://cloud.githubusercontent.com/assets/26583/13210234/fd033690-d8e1-11e5-9370-700cc205f3d0.png)

**Comment by leogopal** [comment]
I am getting the same issue, it won't remember the correct path to VVV

**Comment by bradp** [comment]
Does ~/.vv-config exist? What does it contain?

**Comment by thatryan** [comment]
No, does not exist on my machine. It must have at some point though right? lol

**Comment by leogopal** [comment]
It does exist on mine and it contains the right path. Mine does not suggest
that it is running for the first time. It just asks for the path every time
I run a command. Maybe my issue is separate?

On Tue, 23 Feb 2016 at 7:39 PM Ryan Olson <notifications@github.com> wrote:

> No, does not exist on my machine. It must have at some point though right?
> lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bradp/vv/issues/230#issuecomment-187808997>.
>
-- 
Eternal Smiles
Leo Gopal
http://leogopal.com

**Comment by thatryan** [comment]
Little more info:

So I tried going through the process again with `vv create` and it gave me the same info as above, first time. I followed prompts again and gave it existing directory for everything and had it create new site. 
Which it did.

Still no `~/.vv-config` file, and I then ran `vv delete` ( to remove the dummy site I just made ) and got the same "first time" messages again.

**Comment by bradp** [comment]
You can manually create and edit ~/.vv-config to look like this:

`
{
	"path": "/Users/brad/Sites"
}
`

**Comment by thatryan** [comment]
Thanks, tried that but no go. See screenshot. 

I added path, confirmed path, confirmed working directory, confirmed vvv install, and then got a path error.

![2016-02-26 at 12 33 am](https://cloud.githubusercontent.com/assets/26583/13347169/ca291cd4-dc20-11e5-8ad8-126dfb8b4828.png)

**Comment by axelson** [comment]
I'm also running into this. Running on OS X 10.11.1 (15B42) with a fresh install of VV v1.9.3 (via homebrew).

VVV version is from 2015-09-03

**Comment by thinkhuman** [comment]
I get this too. Very frustrating. No matter what I do, any vv command thinks this is the first time I'm running vv. right now, it's an unusable tool.

**Comment by thinkhuman** [comment]
@bradp Not sure I get the /Sites part. What does that path represent?

**Comment by thinkhuman** [comment]
@bradp Also, why does vv keep asking "Is this where vv is installed?", and if I say no, it asks where *VVV* is installed? Is there an error in this script?

**Comment by bradp** [comment]
@thinkhuman That's probably just a typo.

This is a recurring issue that happens to some people.

Please confirm that ~/.vv-config is readable and writeable.

Also, please provide the output of `vv --debug-vv`.

Thank you.

**Comment by leogopal** [comment]
This is what I get:

```bash
 leogopal@Leos-MacBook-Pro ⮀ ~ ⮀ vv --debug-vv
----------
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path: 	 “/Users/leogopal/vvv”
home: /Users/leogopal

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
----------
[Error] Path specified is not a VVV root directory. Where is VVV installed?
```

**Comment by axelson** [comment]
Here's what I get:

```
$ vv --debug-vv
----------
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path: {  /Users/jason/consult/vagrant-local }
home: /Users/jason

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
----------
[Error] Path specified is not a VVV root directory. Where is VVV installed?
VVV install directory: ^C
zsh: interrupt  vv --debug-vv
```

```
$ cat ~/.vv-config
{ "path": "/Users/jason/consult/vagrant-local" }
$ whoami
jason
$ ls -l ~/.vv-config
-rw-r--r-- 1 jason staff 49 Mar  3 08:33 /Users/jason/.vv-config
```

**Comment by andrewmnz** [comment]
I posted a solution that worked for me in issue #233. Here's the link if you want to give that a go: https://github.com/bradp/vv/issues/233#issuecomment-215620644

**Comment by leogopal** [comment]
Thanks @andrewmnz this worked for me.

**Comment by bradp** [comment]
If there are futher issues, please see #233.

**Comment by bradp** [comment]
`79d92cb75e6c` now gives the command to run to properly create '~/.vv-config` and exposes that after this prompt, so it can be manually run if it doesn't get saved correctly.
