### ISSUE TITLE
Fail: 1

### ISSUE THREAD

**Issue by christianmagill** [bradp/vv#232]
I get a "FAIL: 1" error message after vv commands (create, delete, list, etc.)

Additionally, sites I create often do not show up in @topdown's VVV Dashboard.

I previously removed VVV and installed in a new location, removing and upgrading Virtual Box and Vagrant. I updated the config file to the new locations, and subsequently removed the config file all together and regenerated.

I previously removed and installed VVV at a new location, after which I updated location in config file, and subsequently tried deleting the config file all together.

I have also tried removing and reinstalling VV through Homebrew.

Here's an example: 

Thanks for any help,

$ vv create                                                                                            [0:04:59]
New VVV Site Setup
 Name of new site directory: newsite
 Domain to use (leave blank for newsite.dev):
 WordPress version to install (leave blank for latest version or trunk for trunk/nightly version):
 Install as multisite? (y/N): n
 Git repo to clone as wp-content (leave blank to skip):
 Local SQL file to import for database (leave blank to skip):
 Remove default themes and plugins? (y/N): y
 Add sample content to site (y/N): n
 Enable WP_DEBUG and WP_DEBUG_LOG (y/N): y

About to perform the following:
* Halt Vagrant (if running)
* Create directory newsite in /Users/christianmagill/vvv/www
* Create files vvv-init.sh, wp-cli.yml, and vvv-hosts in directory newsite
* Create file newsite.conf in /Users/christianmagill/vvv/config/nginx-config/sites
* Run `vagrant up --provision` to initialize site

Provisioning Vagrant will do the following:
* Create database newsite
* Install WordPress (release version) in the htdocs directory
* Make the site visible at newsite.dev

 Continue (y/n)? : y
[Success] New VVV setup starting for site 'newsite'
Running vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: Database frameyourcards backed up...
==> default: Database influencebydesign backed up...
==> default: Database newsite backed up...
==> default: Database wordpress_default backed up...
==> default: Database wordpress_develop backed up...
==> default: Database wordpress_trunk backed up...
==> default: Command execution finished.
==> default: Attempting graceful shutdown of VM...
==> default: [vagrant-hostsupdater] Removing hosts
Creating site directory, wp-cli.yml, and vvv-init.sh file...
Done
Adding newsite.dev to new vvv-hosts file...
Done
Creating nginx-config/sites/newsite.conf...
Done
Running vagrant up --provision...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20150609.0.10'. The latest is version '20160303.0.0'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 influencebydesign.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress-trunk.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.50.4  frameyourcards.dev  # VAGRANT: 18f6041cfca87e0012cdf748d8fecf58 (default) / 1116b8ce-2900-43ba-a278-33616503c7e6
==> default: [vagrant-hostsupdater]   192.168.50.4  newsite.dev  # VAGRANT: 18f6041cfca87e0012cdf748d8fecf58 (default) / 1116b8ce-2900-43ba-a278-33616503c7e6
==> default: [vagrant-hostsupdater]   192.168.50.4  testing.dev  # VAGRANT: 18f6041cfca87e0012cdf748d8fecf58 (default) / 1116b8ce-2900-43ba-a278-33616503c7e6
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/christianmagill/VVV
    default: /srv/www => /Users/christianmagill/VVV/www
    default: /srv/log => /Users/christianmagill/VVV/log
    default: /srv/config => /Users/christianmagill/VVV/config
    default: /srv/database => /Users/christianmagill/VVV/database
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: /var/folders/jr/yk8jbpb17w76_9r65n8gfzxw0000gn/T/vagrant-shell20160306-65158-5fqfzr.sh
==> default: Network connection detected...
==> default: Bash profile setup and directories.
==> default: sending incremental file list
==> default: db_backup
==> default: develop_git
==> default: makepot
==> default: vagrant_destroy
==> default: vagrant_halt
==> default: vagrant_suspend
==> default: vagrant_up
==> default: xdebug_off
==> default: xdebug_on
==> default: sent 2.56K bytes  received 187 bytes  5.49K bytes/sec
==> default: total size is 3.48K  speedup is 1.27
==> default:  * Copied /srv/config/bash_profile                      to /home/vagrant/.bash_profile
==> default:  * Copied /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
==> default:  * Copied /srv/config/vimrc                             to /home/vagrant/.vimrc
==> default:  * Copied /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
==> default:  * rsync'd /srv/config/homebin                          to /home/vagrant/bin
==> default: Network connection detected...
==> default:
==> default: Main packages check and install.
==> default:  * php5-fpm                                            5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-cli                                            5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-common                                         5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-dev                                            5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-memcache                                       3.0.8-4build1
==> default:  * php5-imagick                                        3.1.2-1build1
==> default:  * php5-mcrypt                                         5.4.6-0ubuntu5
==> default:  * php5-mysql                                          5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-imap                                           5.4.6-0ubuntu5
==> default:  * php5-curl                                           5.5.9+dfsg-1ubuntu4.14
==> default:  * php-pear                                            5.5.9+dfsg-1ubuntu4.14
==> default:  * php5-gd                                             5.5.9+dfsg-1ubuntu4.14
==> default:  * nginx                                               1.9.12-1~trusty
==> default:  * memcached                                           1.4.14-0ubuntu9
==> default:  * mysql-server                                        5.5.47-0ubuntu0.14.04.1
==> default:  * imagemagick                                         8:6.7.7.10-6ubuntu3
==> default:  * subversion                                          1.8.8-1ubuntu3.2
==> default:  * git-core                                            1:1.9.1-1ubuntu0.2
==> default:  * zip                                                 3.0-8
==> default:  * unzip                                               6.0-9ubuntu1.5
==> default:  * ngrep                                               1.45.ds2-12
==> default:  * curl                                                7.35.0-1ubuntu2.5
==> default:  * make                                                3.81-8.2ubuntu3
==> default:  * vim                                                 2:7.4.052-1ubuntu3
==> default:  * colordiff                                           1.0.13-1
==> default:  * postfix                                             2.11.0-1ubuntu1
==> default:  * ntp                                                 1:4.2.6.p5+dfsg-3ubuntu2.14.04.8
==> default:  * gettext                                             0.18.3.1-1ubuntu3
==> default:  * graphviz                                            2.36.0-0ubuntu3.1
==> default:  * dos2unix                                            6.0.4-1
==> default:  * g++                                                 4:4.8.2-1ubuntu6
==> default:  * nodejs                                              0.10.37-1chl1~trusty1
==> default:  * libsqlite3-dev                                      3.8.2-1ubuntu2.1
==> default: Linked custom apt sources
==> default: No apt packages to install.
==> default: /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
==> default: /usr/lib
==> default: └── npm@3.8.0
==> default: /usr/bin/npm-check-updates -> /usr/lib/node_modules/npm-check-updates/bin/npm-check-updates
==> default: /usr/bin/ncu -> /usr/lib/node_modules/npm-check-updates/bin/ncu
==> default: /usr/lib
==> default: └── npm-check-updates@2.5.8
==> default: pecl/xdebug is already installed and is the same as the released version 2.4.0
==> default: install failed
==> default: ack-grep already installed
==> default: Updating Composer...
==> default: You are already using composer version 3cea62b6ed8220cca53721a3210fbf64a08170dc.
==> default: Changed current directory to /usr/local/src/composer
==> default: Loading composer repositories with package information
==> default: Updating dependencies (including require-dev)
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: Updating Grunt CLI
==> default: Adding graphviz symlink for Webgrind...
==> default: Setup configuration files...
==> default:  * Copied /srv/config/init/vvv-start.conf               to /etc/init/vvv-start.conf
==> default: sending incremental file list
==> default: default.conf
==> default: frameyourcards.conf
==> default: influencebydesign.conf
==> default: local-nginx-example.conf-sample
==> default: newsite.conf
==> default: testing.conf
==> default: sent 6.01K bytes  received 130 bytes  12.28K bytes/sec
==> default: total size is 15.08K  speedup is 2.46
==> default:  * Copied /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
==> default:  * Copied /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
==> default:  * Rsync'd /srv/config/nginx-config/sites/              to /etc/nginx/custom-sites
==> default:  * RVM                                                 1.26.11
==> default:  * Mailcatcher                                         0.6.4
==> default:  * Mailcatcher upstart already configured.
==> default:  * Mailcatcher php5 fpm already configured.
==> default:  * Copied /srv/config/php5-fpm-config/php5-fpm.conf     to /etc/php5/fpm/php5-fpm.conf
==> default:  * Copied /srv/config/php5-fpm-config/www.conf          to /etc/php5/fpm/pool.d/www.conf
==> default:  * Copied /srv/config/php5-fpm-config/php-custom.ini    to /etc/php5/fpm/conf.d/php-custom.ini
==> default:  * Copied /srv/config/php5-fpm-config/opcache.ini       to /etc/php5/fpm/conf.d/opcache.ini
==> default:  * Copied /srv/config/php5-fpm-config/xdebug.ini        to /etc/php5/mods-available/xdebug.ini
==> default:  * Copied /srv/config/memcached-config/memcached.conf   to /etc/memcached.conf
==> default: Restart services...
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Restarting memcached:
==> default: memcached.
==> default: mailcatcher stop/waiting
==> default: mailcatcher start/running, process 8443
==> default: php5-fpm stop/waiting
==> default: php5-fpm start/running, process 8562
==> default: Setup MySQL configuration file links...
==> default:  * Copied /srv/config/mysql-config/my.cnf               to /etc/mysql/my.cnf
==> default:  * Copied /srv/config/mysql-config/root-my.cnf          to /home/vagrant/.my.cnf
==> default: service mysql restart
==> default: mysql stop/waiting
==> default: mysql start/running, process 8606
==> default: Initial custom MySQL scripting...
==> default: Initial MySQL prep...
==> default:
==> default: Start MySQL Database Import
==> default:   * Skipped import of frameyourcards - tables exist
==> default:   * Skipped import of influencebydesign - tables exist
==> default:   * Skipped import of newsite - tables exist
==> default:   * Skipped import of wordpress_default - tables exist
==> default:   * Skipped import of wordpress_develop - tables exist
==> default:   * Skipped import of wordpress_trunk - tables exist
==> default: Databases imported
==> default: Network connection detected...
==> default:
==> default: Installing/updating wp-cli and debugging tools
==> default:
==> default: Updating wp-cli...
==> default: Cannot pull with rebase: You have unstaged changes.
==> default: Please commit or stash them.
==> default: Loading composer repositories with package information
==> default: Updating dependencies (including require-dev)
==> default: Nothing to install or update
==> default: Generating autoload files
==> default: phpMemcachedAdmin already installed.
==> default: Updating Opcache Status
==> default: From https://github.com/rlerdorf/opcache-status
==> default:  * branch            master     -> FETCH_HEAD
==> default: Current branch master is up to date.
==> default: Updating webgrind...
==> default: From https://github.com/michaelschiller/webgrind
==> default:  * branch            master     -> FETCH_HEAD
==> default: Current branch master is up to date.
==> default: Updating PHP_CodeSniffer (phpcs)...
==> default: From https://github.com/squizlabs/PHP_CodeSniffer
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Updating PHP_CodeSniffer WordPress Coding Standards...
==> default: From https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
==> default:  * branch            master     -> FETCH_HEAD
==> default: Already up-to-date.
==> default: Config value "installed_paths" updated successfully; old value was "./CodeSniffer/Standards/WordPress/"
==> default: Config value "default_standard" updated successfully; old value was "WordPress-Core"
==> default: The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP
==> default: PHPMyAdmin already installed.
==> default: Network connection detected...
==> default:
==> default: Installing/updating WordPress Stable, Trunk & Develop
==> default: Updating WordPress Stable...
==> default: Success: WordPress is up to date.
==> default: Updating WordPress trunk...
==> default: Updating '.':
==> default:
==> default: Fetching external item into 'wp-content/plugins/akismet':
==> default: External at revision 1364850.
==> default: At revision 36834.
==> default: Updating WordPress develop...
==> default: Updating '.':
==> default:
==> default: Fetching external item into 'tests/phpunit/data/plugins/wordpress-importer':
==> default: External at revision 1364850.
==> default: At revision 36867.
==> default: Updating npm packages...
==> default:
==> default: VVV custom site import
==> default: Installing WordPress (release version) in newsite/htdocs...
==> default: Downloading WordPress 4.4.2 (en_US)...
==> default: Using cached file '/root/.wp-cli/cache/core/wordpress-4.4.2-en_US.tar.gz'...
==> default: Success: WordPress downloaded.
==> default: Success: Generated wp-config.php file.
==> default: WordPress is already installed.
==> default: Warning: The 'twentythirteen' theme could not be found.
==> default: Success: Deleted 'twentyfourteen' theme.
==> default: Success: Deleted 'twentyfifteen' theme.
==> default: Warning: Can't delete the currently active theme: twentysixteen
==> default: Success: Deleted 'hello' plugin.
==> default: Success: Deleted 'akismet' plugin.
==> default: fatal: Not a git repository (or any parent up to mount point /srv/www)
==> default: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
==> default: /srv/www/newsite
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added frameyourcards.dev from /srv/www/frameyourcards/vvv-hosts
==> default:  * Added influencebydesign.dev from /srv/www/influencebydesign/vvv-hosts
==> default:  * Added newsite.dev from /srv/www/newsite/vvv-hosts
==> default:  * Added testing.dev from /srv/www/testing/vvv-hosts
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 119 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 9562
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: Command execution finished.
[Success] New VVV Site Setup: Done!
Directory: /Users/christianmagill/vvv/www/newsite
URL:       newsite.dev
Username:  admin
Password:  password
FAIL: 1

**Comment by topdown** [comment]
I don't think this is related to VV but probably more of an issue with your VB or VVV install.

One thing that I see in your log is wp-cli install failing because of changes
``` 
default: Installing/updating wp-cli and debugging tools
==> default:
==> default: Updating wp-cli...
==> default: Cannot pull with rebase: You have unstaged changes.
==> default: Please commit or stash them.
```
Not sure if that is the issue or not. But VVV and a lot of tools in my VVV Dashboard rely on WPCLI
So I would get that fixed.

The easiest way to clean this up might be to clone a fresh copy of VVV and copy your sites and configs in and rerun `vagrant up --provision` on the new copy.
You may even need a fresh VB if you made updates in the VB install yourself via SSH. (Which you shouldn't do from what I have read)
Be sure to keep a backup of any important sites you were working on.

**Comment by christianmagill** [comment]
Thanks for the response,

Unfortunately, uninstalling everything (VVV, VV, WP-CLI, VirtualBox, Vagrant) and reinstalling didn't solve the "FAIL:1" issue.

It's interesting that it shows up without any other errors being output. For instance 

$ vv list                                                                                                 [22:21:26]
	* breakingwaves       ( breakingwaves.dev )
	* influencebydesign   ( influencebydesign.dev )
	* wordpress-default   ( local.wordpress.dev ) [VVV default]
	* wordpress-develop   ( src.wordpress-develop.dev ) [VVV default]
	* wordpress-trunk     ( local.wordpress-trunk.dev ) [VVV default]
FAIL: 1

I did figure out that the Dashboard has a cache which was probably causing the other issue.

**Comment by ThatGerber** [comment]
What do you find when you run `vagrant up --provision --debug`? You can redirect the output to a log by appending ` &> vagrant.log`.

**Comment by bradp** [comment]
Closing this. Please reopen if you're still seeing issues.
