### ISSUE TITLE
.vv-config doesn't exist, has been created, still same error.

### ISSUE THREAD

**Issue by reverbsoul** [bradp/vv#233]
Automagically found  
 Is this where vv is installed? (Y/n): y
VVV install directory: /Users/ReverbSoul/test-local

I keep getting this same error. I've answered the question a thousand times. I've created .vv-config (which didn't exist) and have placed it in every folder I can possibly think of. I've cloned vv, and vvv folders directly in to my Vagrant folder (/Users/ReverbSoul/test-local). What am I doing wrong?

Completely disheartened by this whole thing.

Thanks.

**Comment by michaelbeil** [comment]
have you tried a `brew uninstall brad/vv/vv && brew install brad/vv/vv`?

**Comment by reverbsoul** [comment]
Multiple times, yes.

**Comment by thinkhuman** [comment]
I get the same error. It makes this tool unusable, and puts me in quite a bind in my current project.
Also @michaelbeil : It's "bradp", not "brad".

**Comment by reverbsoul** [comment]
I'm still able to use the tool, but I can't make it work in any scripts because of this. Typing the directory starts the tool up, but ultimately I never did find a way to fix this.

**Comment by bradp** [comment]
The best way to solve this is manually creating ~/.vv-config and setting permissions to be world-writeable. 

Or manually creating it with this structure inside:
`
{
	"path": "/Users/brad/Sites"
}
`

**Comment by reverbsoul** [comment]
Where should ~/.vv-config file go? I've done that in every folder related to the project, and still never got it to work.

**Comment by smutek** [comment]
I had this issue as well. I just edited the .vv-config file myself, which solved the problem. 

In my case, VVV is in a folder called vvv, so just open the .vvv-config file in vim, or nano, or whatever.

`vim ~/.vvv-config'

Then update the path and save the file. In my case my install is located in my home directory / sites / vvv 

```bash
{
	"path": "/Users/jimmysmutek/sites/vagrant-local"
}
```

changes to -

```bash
{
	"path": "/Users/jimmysmutek/sites/vvv"
}
```
The next vv-create ran without issue. Hope this is helpful.

**Comment by thinkhuman** [comment]
@smutek Yeah, similar resolution for me. Path and config issues. Thanks for posting that explanation.

**Comment by andrewmnz** [comment]
Had this issue too. Give this a try:

1. Create an empty ~/.vv-config file. (I ran `chmod 777 ~/.vv-config` but I'm not sure that's necessary.)
2. Run `vv --version`

3. Complete the following prompt with an uppercase `Y`:
```
vv version 1.9.3
Automagically found /Users/yourname/VagrantHosts/vvv
Is this where vv is installed? (Y/n): Y
```
NB: I had an existing `VagrantHosts` folder so I put my `vvv` install in there.

Apparently this prompt IS case sensitive, so it needs to be an uppercase `Y`. See issue #213 for more info.

It's also interesting to note that running `cat ~/.vv-config` now shows the path setting in exactly this format:
```
{
    "path": "/Users/yourname/VagrantHosts/vvv"
}
```
Whereas I had previously written this as:
```
{ "path": "/Users/yourname/VagrantHosts/vvv" }
```
Could this be the actual issue @bradp?

**Comment by leogopal** [comment]
@andrewmnz this worked for me.

**Comment by reverbsoul** [comment]
@andrewmnz capital "Y" - Unbelievable....My assumption was always that (Y/n) meant default Y. So even when I did try typing it I didn't capitalize it. Why creating the config file on my own didn't work, I have no idea. But it's fixed now. Thanks for the help @andrewmnz

**Comment by bradp** [comment]
The capital `Y` vs lowercase `y` shouldn't be the issue, but if that helps, great.

If there are further issues, please see #230.

**Comment by bradp** [comment]
`79d92cb75e6c` now gives the command to run to properly create '~/.vv-config` and exposes that after this prompt, so it can be manually run if it doesn't get saved correctly.
