### ISSUE TITLE
Spaces in a `--name` break nginx config and domain mapping

### ISSUE THREAD

**Issue by meitar** [bradp/vv#235]
When a user specifies a `--name` with a space, `vv` will default to using the literal name including spaces in both the `vvv-hosts` and the site's nginx `.conf` file, causing an nginx restart to fail as it encounters a syntax error:

```
==> default: Restart services...
==> default:  * Restarting nginx nginx
==> default: nginx: [emerg] invalid number of arguments in "root" directive in /etc/nginx/custom-sites/BluePrint Test.conf:40
==> default: nginx: configuration file /etc/nginx/nginx.conf test failed
```

The user must override the `--name` argument with an explicit `--domain` to fix the domain mapping, but this will still not fix the nginx issue. A side effect of this is that `vv` will think VVV is not running and skip calling `vagrant halt` because it can not access VVV's `local.wordpres.dev/wp-login.php` page.

# `--debug-vv` output:

```
----------
vv version 1.9.3

vv: /Users/me/bin/vv

vv_config: /Users/me/.vv-config
vvv path: 	 /Users/me/Sites/VVV/
home: /Users/me

tput: 
cat: /bin/cat
curl: /opt/local/bin/curl
brew: 
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
----------
```

**Comment by babxcka** [comment]
Hey sorry to bring up a closed topic, but I've just encountered this problem and can't find much information on how to actually fix it once it's broken...

Any assistance would be legendary!

**Comment by trewknowledge** [comment]
This error happened to me when I created a site that contained a space. I then tried to remove the site using `vv delete` and received the error message mentioned above.

To fix this, I went into my vvv directory to `~vvvfolder/config/nginx-config/sites` and removed the .conf file that was causing me issues.

I then ran `vagrant reload --provision` and the issue went away.

Hope that helps!
