### ISSUE TITLE
Cannot access newdomain.dev

### ISSUE THREAD

**Issue by Alessbruno** [bradp/vv#243]
Hello, I have successfully installed vagrant and vvv on my windows10 machine. I can indeed open http://local.wordpress.dev/ and see the dashboard at vvv.dev; then I ran vv create to set up my own site, and it seems it worked:
![image](https://cloud.githubusercontent.com/assets/8136117/13829877/a8adf986-ebc9-11e5-86c4-0b7234868141.png)
yet, when I open mydomain.dev on the browser, I find the dashboard again!
See screenshot:
![image](https://cloud.githubusercontent.com/assets/8136117/13829910/d62ac146-ebc9-11e5-96e2-56c592b432f1.png)
I am new to vagrant, so I apologize if I am posting an obvious question.
Thanks

**Comment by bradp** [comment]
You'll either have to install the[ vagrant hosts updater plugin](https://github.com/cogitatio/vagrant-hostsupdater), or modify your hosts file to mimic the existing vvv domains with your new domain.

**Comment by Alessbruno** [comment]
Hostupdater is installed but is not working properly - manually updating hosts did the trick. Thanks a lot!

**Comment by weirdwater** [comment]
I have the same problem as @Alessbruno had. I tried looking in my hosts file, but it looks like it's configured correctly. The new sites I added are in the file with a `# VAGRANT:` comment behind it. 

And yet the problem persists. For example, going to local.wordpress.dev opens the local wordpress blog. But going to any newly added blogs I end up at the dashboard. Should I be fixing something in the VM? Or is it something in my Mac's configuration?

**Excerpt from `/private/etc/hosts`:**
```
192.168.50.4  example.dev  # VAGRANT: 4b4a8dfab23654f5b99bb2cc5c3cbeca (default) / 22f49e5a-7472-4951-8506-8c9adc9fe29c
```

**Comment by nandotess** [comment]
Hey @weirdwater, did you fix your problem? I'm having exactly the same problem. My hosts is updated, and the vv tool log success.

Fernando Tessmann — 8:17AM on May 19
Warwick Booth I tried this way too, nothing yet.

1) Installed without any parameters (part 1):
https://www.dropbox.com/s/d1ea9o9fv1x69au/Screenshot%202016-05-19%2008.03.36.png?dl=0

2) Installed without any parameters (part 2):
https://www.dropbox.com/s/ramdh4lgrhcblhz/Screenshot%202016-05-19%2008.04.29.png?dl=0

3) When I access test1.dev (shows dashboard):
https://www.dropbox.com/s/987l3cxvdw58415/Screenshot%202016-05-19%2008.08.07.png?dl=0

4) If I go to Finder see the files in test1 (doesn't shows WordPress files):
https://www.dropbox.com/s/8jihad99gbheirv/Screenshot%202016-05-19%2008.09.13.png?dl=0
