### ISSUE TITLE
Use themes and plugins from local machine in blueprint

### ISSUE THREAD

**Issue by yoxalld** [bradp/vv#244]
I read over the documentation for the blueprints and it sounded like there wasn't a way to install themes and plugins that are stored on my local machine. I just wanted to get some clarification about whether or not this is possible. I'm pretty sure you can install local files with wp-cli so I thought I would check.

Thanks!

**Comment by afragen** [comment]
Not sure this is possible via the blueprint but you can do this via a `Customfile` in your vagrant root directory.

You can see how I do it here, https://gist.github.com/afragen/549cc092a1f61c2a8d7c

The `vvvsites` listed must be created first. After that anytime you `vagrant up` the appropriate symlinks are created.

Obviously anyone else will need to customize this example. The filename must be `Customfile` located in the vagrant root directory.

I'm sure this isn't the only way but it works for me.

**Comment by yoxalld** [comment]
I'm not sure I fully understand what the Customfile does. I'm trying to have VV auto install themes and plugins from local directories on my computer. If I have to do another vagrant up after VV runs it kind of defeats the purpose. Or am I missing a piece? I am still fairly new to these tools.

**Comment by afragen** [comment]
Part of the script passes the site name as a variable. If you know what you're going name the site(s) add the variable there before using `vv create`. The script should fail, gracefully I think, if a site is specified but doesn't exist.

You obviously need to enter the correct paths to your plugins/themes in the script.

**Comment by bradp** [comment]
Blueprints were built with the intention of grabbing from the w.org repos, as well as git repos. Supporting local files is not high on the priority list, but try the method listed above, or feel free to open a PR with fixes.
