### ISSUE TITLE
Redirect Uploads to live/staging site

### ISSUE THREAD

**Issue by BHEADRICK** [bradp/vv#245]
An option to the site creation could be added to prompt for the staging or live site (or both) and then add the following to that site's .conf file:

location /wp-content/ {
if (!-e $request_filename){
rewrite ^/.*/(uploads/.*)$ http://example.com/wp-content/$1 redirect;
}
}

This way, no space or bandwidth needs to be wasted on downloading and storing any images from the live server. 

I'm sure someone better versed in Nginx could alter this so it attempts to load from local before redirecting...

**Comment by bradp** [comment]
The `--images` flag can do this now, but it is not exposed in the wizard. You have to use the `--live-url http://example.com` along with the `--images` flag.
