### ISSUE TITLE
How to clone git repo?

### ISSUE THREAD

**Issue by jspharler** [bradp/vv#254]
When creating a site with vv -c, I get a prompt to `Git repo to clone as wp-content (leave blank to skip):`.  I tried entering the url for my github repo, but that did not work.  How do we get this to clone our repos?

**Comment by bradp** [comment]
What is the url you are using?

Also, please specify the details of `vv` and your system. ( `vv --debug-vv` to get this.)

**Comment by jspharler** [comment]
Thanks Brad,

I am using Windows 10 with the Git bash.  The url is
https://github.com/jspharler/golden.

Here is the output of the command you provided:

Jake@js-desktop  ~/Desktop/vagrant-local/www (develop)
$ vv --debug-vv
----------
vv version 1.9.3

vv: /c/Users/Jake/vv/vv

vv_config: /c/Users/Jake/.vv-config
vvv path:        /c/Users/Jake/Desktop/vagrant-local
home: /c/Users/Jake

tput:
cat: /usr/bin/cat
curl: /usr/bin/curl
which: no brew in
(/c/Users/Jake/bin:/usr/local/bin:/usr/bin:/bin:/cmd:/usr/bin:/usr/share/git-tfs:/c/Users/Jake/AppData/Local/Apps/2.0/PGWVL0M7.TMR/VVM4C0GC.HJK/gith..tion_317444273a93ac29_0003.0000_c74cce3a838f9354:/c/Users/Jake/AppData/Local/GitHub/lfs-amd64_1.1.0:/c/WINDOWS/Microsoft.NET/Framework/v4.0.30319:/c/Program
Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS
Client:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program
Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program
Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files
(x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files
(x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files
(x86)/Zend/MySQL55/bin:/c/Program Files (x86)/NVIDIA
Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program
Files/nodejs:/c/Program Files
(x86)/Brackets/command:/c/HashiCorp/Vagrant/bin:/c/Program Files
(x86)/Skype/Phone:/c/Ruby22-x64/bin:/c/Users/Jake/AppData/Roaming/npm:/c/Users/Jake/vv:/usr/bin/vendor_perl:/usr/bin/core_perl)
brew:
tar: /usr/bin/tar
find: /usr/bin/find
git: /cmd/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /c/HashiCorp/Vagrant/bin/vagrant
----------



Jake Spharler

Email: jake.spharler@gmail.com
<http://www.linkedin.com/in/jakespharler/>

**Comment by afragen** [comment]
@jspharler I think the command you're using wants an entire `wp-content` folder, not just a theme. You might try using a blueprint to add individual plugins and themes.

**Comment by bradp** [comment]
@afragen is correct. The git repo option will clone to the entire `wp-content` directory. If you want to do anything other than this, blueprints are the way to go.
