### ISSUE TITLE
vagrant up --provision vs vagrant provision

### ISSUE THREAD

**Issue by coffeeneed** [bradp/vv#255]
Hi. Just starting to learn this, so I might be way off here. But your readme says I just need to do a "vagrant up --provision" to push WP files inside the created project folder, but nothing happens (even if a script runs for 5 seconds and give no errors).

However; if I run "vagrant provision" the script runs for a longer period of time and then creates a "htdocs"  folder inside the project folder specified in the VV wizard.

So now I have:
vagrant-local\www\mysite\htdocs
However; http://mysite.dev doesnt work it just takes me to default.

So the obvious question has to be; is this meant to be? Is this the correct way to do it? What am I doing wrong?

**Comment by bradp** [comment]
`vagrant up --provision` will run a `vagrant up` and then a `vagrant provision`. It sounds like you have everything running correctly, but your hosts file is not being updated. If you don't have the [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) plugin installed, you may have to manually modify your hosts file.

**Comment by coffeeneed** [comment]
Thanks for reply. I have installed that plugin earlier. I guess I just need to do this one time. I should mention the other sites are working (default sites in VVV).

**Comment by coffeeneed** [comment]
I ran the hostsupdater plugin installer again. Will it suffice to run vagran up again to check if it works now?

**Comment by bradp** [comment]
Try another `vagrant provision`. Also please specify the details of `vv` and your system. ( `vv --debug-vv` to get this.)

**Comment by coffeeneed** [comment]
I did try another vagrant provision. Still mysite.dev shows the default "start page" for vvv:

Home
Repository
phpMyAdmin
phpMemcachedAdmin
Opcache Status
Mailcatcher
Webgrind

However. http://sldgkdslkgjsdglsdglkj.dev cannot be found.

Here is the debug:

vv version 1.9.3

vv: /c/Jobb/testdir2/vv/vv

vv_config: /c/Users/robin/.vv-config
vvv path:        C:/Jobb/testdir2/vagrant-local
home: /c/Users/robin

tput:
cat: /usr/bin/cat
curl: /mingw64/bin/curl
which: no brew in (/c/Users/robin/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/robin/bin:/c/Program Files (x86)/Lenovo/FusionEngine:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Lenovo/Motion Control:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/HashiCorp/Vagrant/bin:/cmd:/c/Jobb/testdir2/vv:/usr/bin/vendor_perl:/usr/bin/core_perl)
brew:
tar: /usr/bin/tar
find: /usr/bin/find
git: /mingw64/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /c/HashiCorp/Vagrant/bin/vagrant

**Comment by coffeeneed** [comment]
I feel bad for bumping this, but I really do need some help regarding this matter. Do you have any ideas, please? :) Much appreciated!

**Comment by coffeeneed** [comment]
Fixed this with reclone of repo and reinstall of Vagrant. Case solved.
