### ISSUE TITLE
navigating to new site

### ISSUE THREAD

**Issue by jordan-webdev** [bradp/vv#256]
Hello, I used vv create to make a test2.dev site in my www folder. However, when I navigate to it, I get the basic vvv.dev screen 

![image](https://cloud.githubusercontent.com/assets/16829239/14962436/c071bb44-106c-11e6-9ad5-d7918d4d2083.png)

Thoughts? I'm on Windows 10. I updated the environment path. I DID remove my vv folder and cloned the repo again, because I forgot to use admin git bash, so I figured I'd try it again in admin.

**Comment by jordan-webdev** [comment]
One thing I noticed is there is no htdocs folder in any new site I create.

**Comment by jordan-webdev** [comment]
Ok, kind of  embarassing- I tried creating a new site inside the www directory in git bash and now it worked! I guess I just wasn't creating anything inside there. I thought you could do commands from anywhere, though (under Usage in the notes, it says "Once installed, you can run vv anywhere you'd like", and it DID "automagically" find the right vagrant-local folder on installation)..Hmm, does this cause concern, since I executed the vv create command outside the www directory? Maybe I have extra wordpress stuff created where it shouldn't be? Think I should reinstall everything? VVV, VV etc..?

**Comment by bradp** [comment]
You should be fine, most likely just needed another provision.
