### ISSUE TITLE
Blueprints not loading

### ISSUE THREAD

**Issue by nanomoffet** [bradp/vv#257]
I can start a new project without a blueprint without issue, but whenever I try to use a blueprint, at best it just doesn't do anything. At worst, the dev site won't load at all.

I tried creating a new instance of WP using the Sample blueprint on the readme, the site comes up but nothing from the blueprint gets implemented - theme, menus, widgets, plugins, nothing. The only thing I see on the console regarding blueprints is this:

==> default: Setting up blueprint sample...
==> default: PHP Notice:  Trying to get property of non-object in /srv/www/sample/vv-install on line 30
==> default: Blueprint set up.

**Comment by nanomoffet** [comment]
I discovered the issue. In the sample blueprint, the last json object for plugins has a comma. Once I removed it, the blueprint processed fine. May want to update the code sample in the readme.

**Comment by bradp** [comment]
Pull requests are welcome!

**Comment by bradp** [comment]
Thanks! Closed in #258
