### ISSUE TITLE
error database connection during creation of new site

### ISSUE THREAD

**Issue by priyabratary** [bradp/vv#261]
1. The version number: vv version 1.9.3
2. Details of VV
vv version 1.9.3

vv: /usr/local/bin/vv

vvv path: 	 /Users/priyabrata/dev
home: /Users/priyabrata

tput: /usr/bin/tput
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/local/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant

3. Problem Details:
Sir, I followed everything and when try to create new site, name:babusona-site.dev,  it shows error database connection and create htdocs folder inside my babusona-site(which I tried to create)

4. Here you can see the screenshot.
![screen shot 2016-05-06 at 10 40 54 am](https://cloud.githubusercontent.com/assets/8244892/15064904/5605b1ee-1377-11e6-9f1f-9b59e18a9adc.png)
![screen shot 2016-05-06 at 10 41 02 am](https://cloud.githubusercontent.com/assets/8244892/15064905/560c3cd0-1377-11e6-9b8d-1c2bb541cb8e.png)
![screen shot 2016-05-06 at 10 41 13 am](https://cloud.githubusercontent.com/assets/8244892/15064906/560c468a-1377-11e6-98b4-ec2ab43e2a33.png)

Can you please help ?

**Comment by jordan-webdev** [comment]
Maybe you need to add a wp-config.php file with all your database settings? You can just look at the wp-config-sample.php file and make a new file called wp-config.php with the same data, but modified to suit your database.

**Comment by priyabratary** [comment]
Thank you very much for your replay but it showing it unable to create database when write terminal as vv create .
Can you please help? Thank you

**Comment by bradp** [comment]
Please update to the latest version of `vv`. If you continue to see these issues, feel free to make a new issue and we'll go from there. Thanks!
