### ISSUE TITLE
Improved handling of spaces and non-alpha-numeric characters in paths

### ISSUE THREAD

**Issue by voltronik** [bradp/vv#264]
Ran into an issue where my VVV path wasn't recognised when using `vv` for the first time. Realised it was because I had a space and some brackets in my folder path which wasn't preserved by vv when entering it into the console. I had to go in and edit the .vv-config file manually and escape them using backslashes.

It's possible this was also the reason why the VVV path wasn't automatically detected in the first place.

**Comment by voltronik** [comment]
This was using 1.10.1.

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.
