### ISSUE TITLE
Cannot access newdomain.dev

### ISSUE THREAD

**Issue by nandotess** [bradp/vv#269]
Hy guys. Sorry, probably this is not a issue with VV, but a issue with me, hehe.

I'm opening a new issue because the #243 is closed. Please see my comment [here](https://github.com/bradp/vv/issues/243#issuecomment-220299016).

I will paste here the problem again:

1. Installed without any parameters (part 1):
https://www.dropbox.com/s/d1ea9o9fv1x69au/Screenshot%202016-05-19%2008.03.36.png?dl=0

2. Installed without any parameters (part 2):
https://www.dropbox.com/s/ramdh4lgrhcblhz/Screenshot%202016-05-19%2008.04.29.png?dl=0

3. When I access test1.dev (shows dashboard):
https://www.dropbox.com/s/987l3cxvdw58415/Screenshot%202016-05-19%2008.08.07.png?dl=0

4. If I go to Finder see the files in test1 (doesn't shows WordPress files):
https://www.dropbox.com/s/8jihad99gbheirv/Screenshot%202016-05-19%2008.09.13.png?dl=0

I verify me hosts, seems to be right. Thanks!

**Comment by voltronik** [comment]
I found this too. 
Running `vagrant up --provision` sorts this but it takes forever, as provisioning does.

**Comment by nandotess** [comment]
For me `vagrant up --provision` doesn't help. =/

**Comment by voltronik** [comment]
What happens when you run `vv --list` - does your site show at the top of the list?

**Comment by bradp** [comment]
Just pushed up 1.10.1, which should now fix this issue.

**Comment by bradp** [comment]
Let's track further issues here: https://github.com/bradp/vv/issues/268
