### ISSUE TITLE
Running `vv vagrant halt` fails silently, required a restart

### ISSUE THREAD

**Issue by voltronik** [bradp/vv#270]
Recently spotted the aliasing that vv has where you can reference vagrant from any folder - very handy!
Unfortunately, I can't get this to work properly. 

If I do `vv vagrant halt` it obviously does something but nothing is outputted in the terminal and it never shuts down the vm properly and so it's stuck in a locked and 'stopping' state. The only way to do this is to kill the VBox-headless process in order to be able to run `vv vagrant up` (or just `vagrant up`) again. Often, the easiest way to do this is to just restart the machine and start over again. 

Not sure if this is related but I've also found `vv vagrant up` monumentally slow to get going which is odd seeing that it knows exactly where vagrant is.

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.

**Comment by voltronik** [comment]
Hi @bradp - I've now updated by original post with the additional details. 
Hopefully you can now help. Also pinged you a Tweet as per the bottom of the README last week regarding something else. Hopefully you can help with that too. 

Jack
