### ISSUE TITLE
Had to recreate vagrant box, now all vv created sites 'lost'

### ISSUE THREAD

**Issue by thinkhuman** [bradp/vv#271]
I had many problems at once with vagrant; TL;DR, I recreated the Vagrant box. Now, I have several sites I created using vv, but they of course are no longer in the Vagrant box. Am I making sense? My goal is to 'recreate' these sites in the box so I can begin working on them again without losing tons of work. 

Can I do that? If so, how? 

fyi: ```vv --list``` correctly shows all my vv created sites.

**Comment by bradp** [comment]
You can try re-running "vv create" for each of the site. The data should stay intact, but I would make a backup beforehand as well.
