### ISSUE TITLE
htdocs not being created

### ISSUE THREAD

**Issue by dsgnr** [bradp/vv#272]
Hello, I have an issue whereby the htdocs and WP files aren't being installed when creating a new vv site. In order for the files to be installed I have to provision the box again manually. I do get a vvv-hosts, vvv-init and wp-cli file, just no htdocs till I provision.

Is there something I have missed?

Thanks!

**Comment by bradp** [comment]
Sounds like an issue with the automatic provisioning.

Do you get any errors in your teminal from `vv`? Also, please send the results of `vv --debug-vv`.

**Comment by dsgnr** [comment]
Sorry, I had another look at this. It seems if vagrant is already up, vv create won't provision the box so no htdocs will be created. However, if vagrant isn't up then it seems to work okay. Is this correct?

Is there a way to change the way Variable VV creates the WP core? I currently have the core files into a subfolder  so ideally would like to replicate that with a new vv site if possible. Say for instance if I wanted to use Bedrock as my core boilerplate... I understand if this isn't possible - would just be really handy :)

**Comment by bradp** [comment]
You can pass the flag `--webroot` in and change the htdocs folder name. If you had your files in the `public_html` folder, you'd run `vv create --webroot public_html` and it will use that during creation.

**Comment by voltronik** [comment]
I noticed that a line '==> default: Running provisioner: shell...' doesn't appear when vv create runs and provisions the box. Running `vagrant provision` does do this for me however.

**Comment by apsolut** [comment]
- just had the same issue (up-halt nothing)... **provision** when up - created htdocs..

**Comment by breadadams** [comment]
Having the same issue, `vagrant provision` fixes it for me, but I've got to run it after every `vv create`.

Any ideas why?
