### ISSUE TITLE
Running `vv vagrant halt` fails silently, requires a restart

### ISSUE THREAD

**Issue by voltronik** [bradp/vv#273]
Version
Experienced this in vv version 1.10.2.

System Details:
----------
vv version 1.10.2

vv: /usr/local/bin/vv

vv_config: ./.vv-config
vvv path:    /Users/Jack/Dropbox\ \(COAS\)/Voltronik/Assets/vagrant-local
home: /Users/Jack

put: 

cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant
----------

Problem
Recently spotted the aliasing that vv has where you can reference vagrant from any folder - very handy!
Unfortunately, I can't get this to work properly.

If I do vv vagrant halt it obviously does something and the title bar of Terminal flickers between commands but nothing is outputted in the terminal and it never shuts down the vm properly and so it's stuck in a locked and 'stopping' state. The only way to do this is to kill the VBox-headless process in the Terminal in order to be able to run vv vagrant up (or just vagrant up) again. Often, the easiest way to do this is to just restart the computer and start over again.

Not sure if this is related but I've also found vv vagrant up monumentally slow to get going which is odd seeing that it knows exactly where vagrant is.

Hopefully you can help. Also pinged you a Tweet as per the bottom of the README last week regarding something else. Hopefully you can help with that too.

Jack

**Comment by bradp** [comment]
Does `vagrant halt` in the directory of VVV work correctly as expected?

**Comment by voltronik** [comment]
Yes it does. 
`vv vagrant halt` takes a long time to execute too.

**Comment by bradp** [comment]
Fixed in #289
