### ISSUE TITLE
htdocs Folder Not Created

### ISSUE THREAD

**Issue by Gemfruit** [bradp/vv#284]
I updated my setup this morning, updating vv to 1.10.2, and now when I use vv create, It goes extremely fast, and never creates the htdocs folder inside of the directory. It does create the site directory, which contains vvv-hosts, vvv-init, and wp-cli.yml, but no htdocs, no Wordpress, etc.

Any idea what's going on?

git bash output - http://pastebin.com/KznwxYr6

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.
