### ISSUE TITLE
vv doesn't install wordpress

### ISSUE THREAD

**Issue by reneruiz** [bradp/vv#287]
I'm running into an issue where the `vv create` process ends once the site www dir is created and the 3 files are copied inside. WordPress doesn't get installed.

![Screenshot](https://d1zjcuqflbd5k.cloudfront.net/files/acc_3082/11CIM?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202016-06-23%20at%2009%3A33%3A12.png&Expires=1466689137&Signature=EvoPB2G3MH3u9bPbZubNRMt~3gxkhCb8dKJNKZH5oZMpPRAZKqMoHKfnC6RQf1yjLZTbeFXKjaUSFxrjaF2gc10Mxo4SqBhqpRbE4cFEpdr9ovg0weo4wSNHHZqj5B8k37GVzB7ckF9ytdk5qqnn447uDd29VY0loRLM5F4ZJV8_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by bradp** [comment]
Same issue as https://github.com/bradp/vv/issues/286. for now, run `vagrant provision` to fix.
