### ISSUE TITLE
Does not vagrant halt when creating a new site under Windows 10

### ISSUE THREAD

**Issue by benlumia007** [bradp/vv#291]
I'm not sure if this an issue or what when using VVV and vv under Windows 10.  I've been trying to figure out why when you do  vv create and enter a name for, instead of vagrant halt, it skips it and finishes without rebooting, so i have to do a vagrant provision for it to take effect. 

Any idea.

**Comment by bradp** [comment]
Fixed in #289, I just need to tag and release a new version with that.
