### ISSUE TITLE
It still doesn't work... 

### ISSUE THREAD

**Issue by benlumia007** [bradp/vv#292]
benlumia007@saruman-desktop MINGW64 ~/WordPress (develop)
**$ vv create**
New VVV Site Setup
 Name of new site directory: sandbox
 Domain to use (leave blank for sandbox.dev):
 WordPress version to install (leave blank for latest version or trunk for trunk/nightly version):
 Install as multisite? (y/N): N
 Git repo to clone as wp-content (leave blank to skip):
 Local SQL file to import for database (leave blank to skip):
 Remove default themes and plugins? (y/N): y
 Add sample content to site (y/N): y
 Enable WP_DEBUG and WP_DEBUG_LOG (y/N): y

About to perform the following:
* Halt Vagrant (if running)
* Create directory sandbox in /c/Users/benlumia007/WordPress/www
* Create files vvv-init.sh, wp-cli.yml, and vvv-hosts in directory sandbox
* Create file sandbox.conf in /c/Users/benlumia007/WordPress/config/nginx-config/sites
* Run `vagrant up --provision` to initialize site

Provisioning Vagrant will do the following:
* Create database sandbox
* Install WordPress (release version) in the htdocs directory
* Make the site visible at sandbox.dev

 Continue (y/n)? : y
[Success] New VVV setup starting for site 'sandbox'
Checking to see if vagrant halt should be run...
Vagrant not running, skipping `vagrant halt`...
Creating site directory, wp-cli.yml, and vvv-init.sh file...
Done
Adding sandbox.dev to new vvv-hosts file...
Done
Creating nginx-config/sites/sandbox.conf...
Done
Running vagrant up --provision...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: VirtualBox VM is already running.
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 sandbox.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress-trunk.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Running triggers after up...
==> default: Executing command "vagrant ssh -c vagrant_up"...
==> default: Command execution finished.
[Success] New VVV Site Setup: Done!
Directory: /c/Users/benlumia007/WordPress/www/sandbox
URL:       sandbox.dev
Username:  admin
Password:  password

benlumia007@saruman-desktop MINGW64 ~/WordPress (develop)

**Comment by benlumia007** [comment]
VVV isntallation is: c\users\username\WordPress\
vv installation is in c:\ussers\username\WordPress\vv

**Comment by bradp** [comment]
See #291
