### ISSUE TITLE
Linux installation - bash: vv: command not found...

### ISSUE THREAD

**Issue by WEBIDIA** [bradp/vv#293]
I've followed the instructions for Linux installation but when I run the command 'vv list' I get the error:

bash: vv: command not found...

I'm fairly new to Linux so I might be missing something obvious. If I run the script using 'bash /usr/local/bin/vv' I get the script options etc but using the vv command does not work.

I'm running Fedora 24 if that makes any difference. Thanks in advance.

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.
