### ISSUE TITLE
bash vv doesn't work on virtualbox 5.1

### ISSUE THREAD

**Issue by benlumia007** [bradp/vv#294]
vv doesn't seem to run command not found, using virtualbox 5.1

**Comment by benlumia007** [comment]
nevermind..

**Comment by benlumia007** [comment]
actually it doesn't seem to work!

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.
