### ISSUE TITLE
Removing default themes (and plugins)

### ISSUE THREAD

**Issue by zanematthew** [bradp/vv#295]
When the following option is set `Remove default themes and plugins? (y/N): y`

The default theme **twentysixteen** is not removed. Is this the expected behavior as you may need to have at least one active theme.

**Comment by bradp** [comment]
It should be deleting 2016, not sure why it isn't.

Here's the relevant line of code, if you want to take a look / send a PR: https://github.com/bradp/vv/blob/master/vv#L998
