### ISSUE TITLE
vv create doesn't create /htdocs

### ISSUE THREAD

**Issue by BrevAlessio** [bradp/vv#299]
Hi,  running `vv create`doesn't create an `htdocs` folder, so neither a wordpress installation. 
I also tried to run `vagrant provision` after the create command but nothing changes. I noticed the following output during the create process:
`==> default: Network connection not detected. Unable to reach google.com...`
`==> default: No network connection available, skipping package installation`

I think it could be related, is that right? However I'm not sure where to look for a fix.

`vv version 1.10.2`
## `vv --debug-vv

/usr/local/bin/vv: riga 1482: version: comando non trovato

vv: /usr/local/bin/vv

vv_config: /home/alessio/.vv-config
vvv path:    /home/alessio/Progetti/vagrant-local
home: /home/alessio

tput: 
cat: /bin/cat
curl: /usr/bin/curl
brew: 
tar: /bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /bin/sed
paste: /usr/bin/paste
## vagrant: /usr/bin/vagrant

`

**Comment by BrevAlessio** [comment]
Sorry, think it was a VVV issue.
Seems solved just by commenting the  line in the provision.sh file.

`network_check() {`
  ` network_detection`
 `  if [[ ! "$ping_result" == "Connected" ]]; then`
`     echo -e "\nNo network connection available, skipping package installation"`
`     #exit 0`
`   fi`
`}`

**Comment by bradp** [comment]
Also being tracked in https://github.com/bradp/vv/issues/324. This is on my "must-fix" roadmap to do as soon as possible.
