### ISSUE TITLE
Missing htdocs file after vv create

### ISSUE THREAD

**Issue by breadadams** [bradp/vv#300]
I'm having what _seems_ to be the same issue as @dsgnr here: https://github.com/bradp/vv/issues/272

`vagrant provision` "fixes" it, but it's tedious having to run this after every setup, especially if on a weak connection (tethered 3/4G, etc.) as it downloads latest bundles of WP.

Also recently noticed that this _doesn't_ work for multisite installs, even after `vagrant provision`, there is no htdocs folder.

Help, please? 😄

**Comment by dsgnr** [comment]
I think there was a temperamental way around it by doing this when vagrant was halted. I have however, moved away from Vagrant altogether now so I didn't spend too long trying to resolve this properly @breadadams

**Comment by breadadams** [comment]
Aha, I see. I was running it while vagrant was _up_, tried when halted but throws

```
➜  vagrant-local vagrant provision
==> default: VM is not currently running. Please, first bring it up with `vagrant up` then run this command.
```

Well, thanks anyhow @dsgnr, will wait see if @bradp has any insight.

**Comment by dsgnr** [comment]
Sorry @breadadams, I meant try the vvcreate whilst the box is off

**Comment by breadadams** [comment]
Aha, just tried that now and got different results.

After the setup, when I went to the .dev domain, I was presented with the Wordpress "new installation" screen. Even though I got the typical:

```
URL:       X.dev
Username:  admin
Password:  password
```

in terminal.

**Comment by bradp** [comment]
Being tracked in https://github.com/bradp/vv/issues/324. This is on my "must-fix" roadmap to do as soon as possible.
