### ISSUE TITLE
VV Deosn't complete wordpress installation

### ISSUE THREAD

**Issue by mohlp** [bradp/vv#301]
Hello, 

I had experienced a small issue with my last update of vv , which is when i create new wordpress site using vv create and following all the steps and when it's done it gives me as usual the example.dev link and the login info,
but when i try to open the site example.dev it redirects to /wp-admin/install.php and asks for installation which i think i didn't experience before at all.
and when i do the installation some errors shows on the vvv dashboard.

please, any suggestions?

**Comment by bradp** [comment]
Thanks for using `vv`, and I'm sorry to see you're having issues.

Please follow the directions in the [https://github.com/bradp/vv/blob/master/CONTRIBUTING.md](contributing) document for how to post an issue.

I'm closing this issue now, but feel free to open a new issue with the correct format, especially providing the output of `vv --debug-vv` in your issue.
