### ISSUE TITLE
Install WordPress in a subdirectory?

### ISSUE THREAD

**Issue by mishtershmart** [bradp/vv#303]
Howdy,

Is it possible to install WordPress in a subdirectory using VV? This isn't an MU installation – just a regular installation with a WP in a dir called `wordpress`.

Thanks!

**Comment by bradp** [comment]
There is a `--webroot` flag that you can pass into `vv create` to change the default `htdocs` folder. You would call `vv create --webroot wordpress` to name the folder `wordpress`.
