### ISSUE TITLE
Init bash script missing shebang and adding multiple empty lines

### ISSUE THREAD

**Issue by franz-josef-kaiser** [bradp/vv#309]
The setup for the `vv-init.sh` script is missing [a shebang](https://github.com/bradp/vv/blob/3b1255716968e0a081f768fe49de04928f07b33b/vv#L1044), which probably should be `#!/usr/bin/env bash`. Also it is adding [multiple empty lines](https://github.com/bradp/vv/blob/3b1255716968e0a081f768fe49de04928f07b33b/vv#L1054-L1067), which could be avoided by checking if the variable is empty as `""` seems to be the default for all of them:

    [ -z "${VAR}" ] || echo "  $maybe_remove_defaults"

If there is the need to account for other defaults than `""`/ empty, please see [this ServerFault answer](http://serverfault.com/a/382740/120233).

**Comment by bradp** [comment]
The shebang doesn't need to exist, as the file just gets sourced, not executed. 

Thanks for the good advice on the empty lines, added in 4ff84ed6c753.
