### ISSUE TITLE
Wordpress isn't installed by VV

### ISSUE THREAD

**Issue by NitAGE** [bradp/vv#310]
vv version 1.11
## $ vv --debug-vv

/c/Program Files/vv/vv: line 1482: version: command not found

vv: /c/Program Files/vv/vv

vv_config: /c/Users/xxx/.vv-config
vvv path:  /N/LocalSite/VVV
home: /c/Users/xxx

tput:
cat: /usr/bin/cat
curl: /mingw64/bin/curl
which: no brew in (/c/Users/xxx/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/xxx/bin:/c/program files/graphicsmagick-1.3.21-q16:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Users/xxx/AppData/Local/Atlassian/SourceTree/git_local/libexec/git-core:/c/Program Files/vv:/c/Program Files/nodejs:/c/xampp/php:/c/ProgramData/ComposerSetup/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/bin:/usr/bin:/c/Development/android-sdk/platform-tools:/c/Development/android-sdk/tools:/c/HashiCorp/Vagrant/bin:/c/Users/xxx/AppData/Roaming/npm:/c/Ruby22/bin:%USERPROFILE%/AppData/Local/Microsoft/WindowsApps:/usr/bin/vendor_perl:/usr/bin/core_perl)
brew:
tar: /usr/bin/tar
find: /usr/bin/find
git: /mingw64/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
## vagrant: /c/HashiCorp/Vagrant/bin/vagrant

When launch "vv create" we get errors and worpress doesn't install.
we get the following errors:

==> default: Installing/updating WordPress Stable, Trunk & Develop
==> default: Updating WordPress Stable...
==> default: PHP Fatal error:  Call to undefined function apply_filters() in /srv/www/wordpress-default/wp-includes/load.php on line 317
==> default: Updating WordPress trunk...
==> default: Updating '.':

==> default: Downloading WordPress 4.6.1 (en_US)...
==> default: Success: WordPress downloaded.
==> default: Success: Generated wp-config.php file.
==> default: PHP Fatal error:  Call to undefined function apply_filters() in /srv/www/prova/htdocs/wp-includes/load.php on line 317
==> default: /srv/www/prova

then others errors related to the fact wordpress isn't installed.

After the finish of the provisioning, going to the website just created we are redirected to the wordpress install page (install.php)

Thanks
Nitage

**Comment by bradp** [comment]
Being tracked in https://github.com/bradp/vv/issues/324. This is on my "must-fix" roadmap to do as soon as possible.
