### ISSUE TITLE
Cannot access my created sites' URL's?

### ISSUE THREAD

**Issue by Pturner645** [bradp/vv#316]
I am receiving the error messages: 

==> default: nginx: [warn] conflicting server name "greenchain-eng.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name "greenchain-eng.dev" on 0.0.0.0:443, ignored
==> default: nginx: [warn] conflicting server name "greenchain-eng.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name "greenchain-eng.dev" on 0.0.0.0:443, ignored

when typing vagrant up in my vagrant-local folder.

When I try and access the sites I aam taken to a page stating:

This site can’t be reached
greenchain-engineering.dev refused to connect.
Search Google for greenchain engineering dev 

Would be enormously grateful if anyone can help me out here?

**Comment by bradp** [comment]
Being tracked in https://github.com/bradp/vv/issues/324. This is on my "must-fix" roadmap to do as soon as possible.
