### ISSUE TITLE
Unable to access newly created sites?

### ISSUE THREAD

**Issue by Pturner645** [bradp/vv#318]
When I attempt to access my newly created site I am taken to this page:

'Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.'

Instead of the home page?

Anyone have any ideas?

**Comment by Idealien** [comment]
Does your /srv/www/[selected-domain]/ path contain an htdocs folder after create step completes?

I setup a new VVV and VV installation and had similar issue which resolution was to manually run the vvv-init.sh script and it completed the rest of setup successfully.

Related #319 has a bit more info on similar provision issue.

**Comment by benlumia007** [comment]
Please see ticket #324

**Comment by bradp** [comment]
Being tracked in https://github.com/bradp/vv/issues/324. This is on my "must-fix" roadmap to do as soon as possible.
