### ISSUE TITLE
Can't run vv under win10

### ISSUE THREAD

**Issue by Humanitech** [bradp/vv#322]
Hi, I'm trying to install vv on my Pc but it seems I couldn't find out a way..
I tried several times, using an administration user profile on my machine.
I applied all the rules/steps of the installation guide for Windows install. No way. I tried also inside Ubuntu VM using Linux steps. No way.

Trying to execute vv from ssh shell the message is "No such file or directory". Trying to execute vv from vagrant VM in Windows, using Git Shell, a Windows prompt asks me which is the application needed to open such kind of file (!).

It seems no operating systems recognises vv as an executable file. I also forced chmod 777, but nothing.

I thought It could be a problem related to 64 bit environment and the absence of support for 32 bit file in Ubuntu, so I installed some libraries to add the architecture i386 on Linux VM. No way. I obtain always a message like this when I write "bash vv" from ssh terminal... 

![image](https://cloud.githubusercontent.com/assets/20318613/20033354/d39c448a-a39e-11e6-85c8-e7ffa133d7a7.png)

Any suggestions?
Thank you very much for any help.. 
dario

**Comment by Humanitech** [comment]
I finally find out the way. I solved by installing two components I forgot during my VVV Vagrant installation: 1) VirtualBox Extension Pack; 2) [Git Bash](https://git-for-windows.github.io/). My error was to use [GitHub Desktop](https://desktop.github.com/) and  Git Shell instead of Git Bash for Windows.
Now everything works fine.
Thank you.
dario

**Comment by VWinDev** [comment]
@Humanitech  what is the need for VirtualBox Extension Pack?
