### ISSUE TITLE
Vagrant Ubuntu Box

### ISSUE THREAD

**Issue by elpuas** [bradp/vv#325]
Hi i'm getting nuts here, have hours trying to solve this: 
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog.

when i add the url to the config.vm.box i get this
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

any help would be much appreciate

i'm running macos sierra and vagrant 1.8+

**Comment by benlumia007** [comment]
are you using virtualbox 5.1.8, if you are, downgrade to 5.1.6, 5.1.8 won't work well with vagrant at the moment.

**Comment by elpuas** [comment]
Will give it a try

**Comment by elpuas** [comment]
Nope no luck
 The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: ( nothing show here ),
it was working on my old mac, but i have to cahnge it and the new one runs MACOS Sierra, 

 i guess i will go back to my old and trusty MAMP

**Comment by benlumia007** [comment]
SOrry if that it didn't work. Im running MacOS Sierra i believe and it works for me. but i guess it doesn't work for some people. I use MAMP too. i like it.

**Comment by elpuas** [comment]
yeah i'm still trying different solutions, can't give up so easy. thanks for your help.

**Comment by benlumia007** [comment]
@elpuas 
yeh vvv is good, i love it, but as you can tell, when we do updates to the latest software or app, stuff breaks, I spent hours on my side trying to figure out, but then, like i said, some solutions doesn't work well with other people sigh. I've been using vvv on PC and Mac and Linux so, different OS different outcomes..

**Comment by elpuas** [comment]
Hey Benjamin i made it! i run:  "sudo rm /opt/vagrant/embedded/bin/curl" to add the ubuntu box and now is running fine again

**Comment by benlumia007** [comment]
My Setup now is
VirtualBox 5.1.6
Vagrant 1.8.5
vvv 1.4.0
vv 1.12
