### ISSUE TITLE
Can't get multisite to work

### ISSUE THREAD

**Issue by rootion** [bradp/vv#329]
I am having issues running installing a multisite WP installation. This is what I do:

1.  Create multisite running `vv create -d multisite.dev --multisite subdirectory -x`

2. Edit vvv-hosts file in `~/Path/to/VVV/www/multisite/vvv-hosts` according to the documentation, adding each subdomain on a new line. It looks like this:
```
multisite.dev
en.multisite.dev
es.multisite.dev
```
3.  Run `vagrant reload --provision`

Here I receive some warnings:
```
==> default: nginx: [warn] conflicting server name "es.multisite.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name "es.multisite.dev" on 0.0.0.0:443, ignored
==> default: nginx: [warn] conflicting server name "es.multisite.dev" on 0.0.0.0:80, ignored
==> default: nginx: [warn] conflicting server name "es.multisite.dev" on 0.0.0.0:443, ignored
```

I have the domain and subdomains in the VVV dashboard, but only multisite.dev will run the installer. The en.multisite.dev will redirect to the dashboard and the es.multisite.dev will time out.

What's wrong with the installation?

**Comment by bradp** [comment]
Closing this, I'm going to start tracking 2.0 support in #348.
