### ISSUE TITLE
Is vv --create supposed to do a complete installation?

### ISSUE THREAD

**Issue by estevancarlos** [bradp/vv#346]
I've had trouble with vv relating to ./vvv-init.sh. After manually executing the file, I ran what may be a successful create task but I can't tell. After running --create, my Wordpress install still needed be completed by connecting it to the database. I mistakenly assumed this was a part of the automated process but maybe it isn't. Can anyone confirm?

**Comment by kennyr87** [comment]
I had the same problem.  Looks like a problem on line 1039.

`wp core $install_text --url=$domain --title=\"$site\" --admin_user=$username --admin_password=$password --admin_email=$email --allow-root`

$install_text is not getting set.

**Comment by bradp** [comment]
Closing this, I'm going to start tracking 2.0 support in https://github.com/bradp/vv/issues/348.
