### ISSUE TITLE
Not working with VVV2...I think

### ISSUE THREAD

**Issue by rebeccahum** [bradp/vv#351]
I don't think the current version of VV is working with the VVV2. Just had fresh install of VVV2 and trying to use VV on Windows, but I am getting the error, "vv: command not found". It's been path'd correctly. However, it was working on my old machine a few months ago prior to VVV2 being released.

**Comment by rebeccahum** [comment]
Nevermind for Windows 10, I just needed to download Git Bash and run it off of there. 

cmd bash vv did not work for me.

**Comment by debabratakarfa** [comment]
I try to use vv create command but it not adding to the .dev domain to list and not working too
