### ISSUE TITLE
Allow use of existing directory in `www/` for new site setup

### ISSUE THREAD

**Issue by creativecoder** [bradp/vv#40]
Sometimes I want to setup vvv site within an existing directory in `www/`. Maybe I've already cloned a git repo into that folder, or maybe I want to rerun site configuration for some reason, without manually changing the files.

Seems like this has a few implications
- Disable directory check when prompted for site name. Instead check for nginx configuration file.
- Don't offer to clone a git repo, if the directory already exists
- Conditionally do `mkdir`, only if the directory isn't already there
- Anything I'm missing?

I'll submit a pull request if you think this would be a good feature to add. Thanks, Grant

**Comment by joshua-chavanne** [comment]
Any word on this?  I just installed VV and am porting all of my sites into a VVV instance, worked out all the kinks with that and was wondering why the legacy sites I had are not listed in a `vv list`, found this and was wondering if there is a way of `registering` legacy sites into vv?
