### ISSUE TITLE
Options that don't require a value can't be grouped

### ISSUE THREAD

**Issue by creativecoder** [bradp/vv#43]
I would expect option flags that don't take values to be valid when grouped like so, `vv -cf` but this doesn't work.

**Comment by creativecoder** [comment]
I looked into parsing arguments differently so this could be supported:

- Use `getopts` built in bash scripting command
Problem: doesn't support long options

- Use `getopt` binary to parse options
Problem: getopt version that ships with OS X doesn't support long options. Would need to use the gnu version of getopt, which creates an additional dependency for vv

Unless anyone has another idea--looks like this is more trouble than it's worth.

**Comment by bradp** [comment]
The only other idea I could think of is mapping out all possible permutations, or figuring that out at runtime.

Doesn't seem worth it to me either.

**Comment by bradp** [comment]
We'd also have to rename a lot of the short commands, as 
-f -p are two commands available, as is -fp
