### ISSUE TITLE
Feature request: Add option to accept default prompts

### ISSUE THREAD

**Issue by clifgriffin** [bradp/vv#44]
I'm currently master (future 1.4.7).  I have an alias setup that looks like this:
`alias newcgd="vv -c --git-repo https://github/mycoolrepo.git -n"`

This allows me to run:
`newcgd test` 

And save quite a few keystrokes.  However, it would be super awesome if there were a flag I could pass that says "accept defaults and run" so I don't get prompted for things like blueprint, defines, etc.

**Comment by bradp** [comment]
Added in 65bde633fccb32f49b29c60d8fe0890db53801b8 and will be in the next release, after a bit more testing.

**Comment by clifgriffin** [comment]
Woo!!

**Comment by bradp** [comment]
Feel free to clone the repo and play around on the master branch.

If you want to test, while keeping the stable version of VV installed, simply clone this repo and then go in the folder and run `./vv`

You might potentially get update notifications, but just ignore them.

**Comment by clreed87** [comment]
Does <code>--defaults</code> bypass the wizard in each <code>vv create</code> that it is passed in or does it disable the wizard in VV all together?

**Comment by bradp** [comment]
Just disables it for that current site you're creating.
