### ISSUE TITLE
Deal with sites in subfolders

### ISSUE THREAD

**Issue by defries** [bradp/vv#46]
I like to keep my ```/www/``` folder a little bit organised with various folders containing a certain group of sites. It'd be wonderful if VV could create and delete in specified subfolders.

**Comment by clreed87** [comment]
+1 on this. I'd really like to be able to organize my project sites withing the www folder.

**Comment by bradp** [comment]
Related to #3  and #2.

**Comment by bradp** [comment]
This functionality is now in the master branch. Using the `-fsf` flag, you can pass in a path with a subfolder to use. For example, if you have a client/ folder that you want to store projects under, you would do `vv create -fsf www/client`, and it will create the site there.

`vv list` doesn't work 100% yet with it, but creation seems to work perfectly.

**Comment by bradp** [comment]
And `vv list` is fixed in 5044c5240438, so subfolder sites should work great.
