### ISSUE TITLE
[Error] Path specified is not a VVV root directory.

### ISSUE THREAD

**Issue by zu** [bradp/vv#56]
I had VVV installed before and also VV. I then removed VVV and later reinstalled it. Now VV seems to be still installed in an older version but whatever I try to do I get the message "[Error] Path specified is not a VVV root directory." How can I either remove VV or update it or how can I give VV the right path information or "Otherwise you'll want to clone and edit your $PATH to include the vv core file."? is what the README says but I don't understand.

**Comment by bradp** [comment]
You can edit ~/.vv-config to have your correct path. Or remove that file and VV will prompt you again.

**Comment by zu** [comment]
ok, thanks. works

**Comment by spigotdesign** [comment]
Sorry to reopen this, but I'm having the same issue. VVV asks every time where VVV is installed, even though ~/.vv-config is there and contains the correct path.

**Comment by bradp** [comment]
@spigotdesign Can you send me your ~/.vv-config?

**Comment by spigotdesign** [comment]
```
{
	"path": "/Users/bryan/Documents/Work/Sites/vvv/VVV-master"
}
```

**Comment by bradp** [comment]
Is that where VVV is installed?

**Comment by spigotdesign** [comment]
Actually it's installed one dir back in 'vvv'  

I've edited it and all is good, sorry for the trouble! Faceslap.

**Comment by onthisearth** [comment]
I have the same problem on my Windows machine: VVV asks every time where VVV is installed, even though ~/.vv-config is there and contains - hopefully - the correct path. It is the path to the Vagrantfile, isn't it?

**Comment by wester97** [comment]
I am having this issue as well.  Also tried manually adjusting the config.

**Comment by simonmacfadyen** [comment]
I am also having this issue, after installing via brew on mac.

**Comment by cc590p** [comment]
Same issue. on a mac. cant find .vv-config file to even manually edit. for every command it cannot find the path to VVV

**Comment by BorislavZlatanov** [comment]
On Windows, I think I managed to solve this. First, I installed Git Bash (couldn't get it to work with cmd.exe). Second, I made sure that I was in my vv installation directory when vv was asking "Is this where vv is installed?" and then I entered Y. Third, I saw in the vv file the lines:

`if [ ! -e "$(eval echo "${path//>}")/Vagrantfile" ]; then
			error "Path specified is not a VVV root directory. Where is VVV installed?"`

So this showed me how exactly the program is looking for the path to the Vagrantfile. Then what I entered in Git Bash was `D:/vagrant-local` (yes, using forward slash, and no trailing slash). 

And finally, on each command it was asking me again for those paths, so I started suspecting permissions issues (i.e. it can't write the config file). Then I manually opened .vv-config which was in C:\Users\myuser and entered there the path to VVV (`D:/vagrant-local` in my case).

Everything seems to be working now. :)

**Comment by bradp** [comment]
I plan to add more checks / help around this area in 2.0 : https://github.com/bradp/vv/issues/161

**Comment by reykan** [comment]
I had the same issue and realized it was having trouble with permissions. File .vv-config was assigned to root instead to my username. I fixed it with  - sudo chown user .vv-config

Hipe this helps.

**Comment by bradp** [comment]
That is usually the issue with the vv-config issues. My plan is to check ownership before attempting to write to it, and output the error, rather than failing silently, as it currently is.

**Comment by Cardy** [comment]
Please add a note in the README for Windows users (like me): when you are asked to specify path,it must be with forward slash as already stated from @BorislavZlatanov in the comments above

**Comment by JamesICT** [comment]
I am using Windows 10
Using Gitbash

Installed in c:\vv

Nothing I enter seems to work

All I see in bright red letters is
"Path specified is not a VVV root directory. Where is VVV installed?"

Can anyone tell me what to do exactly?

**Comment by nuruddinbadawi** [comment]
I'm having the same issue, and by the default, I don't found .vv-config file I created by myself and add
{
   "path" : "/Users/nuruddin/servers/wordpress/"
}
but still same issue nothing change .

**Comment by eriktdesign** [comment]
Try /c/users/...

**Comment by nuruddinbadawi** [comment]
i have Mac OS

**Comment by sumnermic** [comment]
Hello @nuruddinbadawi 

Have you found a solution for you already?

Kind regards,
