### ISSUE TITLE
Only provision the new site

### ISSUE THREAD

**Issue by rezzz-dev** [bradp/vv#58]
Not sure if this is possible or not, but figured I'd see what you think.

I use the same VVV instance for multiple sites.  But when I create a new site, it'll go through all the sites on the instance and create the db, install files, etc.  It'd be cool if there was a way to just add the new site during the creation and not re-create the whole entire instance.

Does this make sense at all?

**Comment by bradp** [comment]
I'm not sure if there is a way to do this with the way VVV is setup.

VV is basically creating files that VVV executes on provision.
