### ISSUE TITLE
Feature request: new options on `vv create`

### ISSUE THREAD

**Issue by fyaconiello** [bradp/vv#62]
I have run into cases during <code>vv create</code> where I think some basic flags/options should be available

1. Accept a SQL file for an existing DB. I imagine this would copy the .sql to the database/backups folder prior to vagrant provision.
2. Allow override on certain settings for the wp_config file. I really want to be able to specify the table prefixes when switching existing projects over to my VVV workflow.

Am I missing the point?
Does anything like this exist? 
If I wanted to dig in and contribute where would I start?

**Comment by bradp** [comment]
Those are great suggestions.

In fact, I think I have code for the DB stuff laying around somewhere, as I used to have that.

I'd for sure like to implement both of those. If you'd like to contribute, I'd say take a look at how some of the current flags are implemented. Like the git repo cloning or the sample content.

**Comment by bradp** [comment]
Database import: https://github.com/bradp/vv/issues/26
wp_config settings can be set with the "defines" of blueprints.
