### ISSUE TITLE
Option to copy arbitrary files into site root on creation

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#64]
I often create my WordPress git repos at the site root level and then use the .gitignore file to only version control files in the wp-content directory (except for uplooads).  It would be nice to be able to automatically bring that file in or clone it from a git repo at the site root level.

I know we can clone wp-content folder on creation now, I'd just like to do the same thing up one level at the site root.

Sorry if there is a way to do this already--I'm still trying to learn.

**Comment by bradp** [comment]
I think this is a great idea, I can see a lot of uses for this.

**Comment by bradp** [comment]
Closing, as this will be really simple when #67 is finished.

**Comment by dendeffe** [comment]
@bradp Is this possible now? If so, is there an example somewhere?
