### ISSUE TITLE
Feature Request - RSA (passwordLess SFTP)

### ISSUE THREAD

**Issue by shaneholloman** [bradp/vv#65]
**Mega praises to you @bradp and thank you!**
 I would like the possibility to use a rsa key to push to a server - no password sftp

What do you think?

**Comment by bradp** [comment]
You should be able to simply leave the password out of the config.

VV just implements Vagrant push, so there may be more documentation here: https://docs.vagrantup.com/v2/push/ftp.html

**Comment by shaneholloman** [comment]
I see nothing at this time to support this here: https://docs.vagrantup.com/v2/push/ftp.html I am currently hitting IRC and NewsGroups to find solution. 

Maybe a simple solve would be an option in `vv` to allow us to leave the password blank during the deployment setup via `vv`?
