### ISSUE TITLE
Replace current image proxy method

### ISSUE THREAD

**Issue by thenoelforte** [bradp/vv#66]
I tried passing in the `-i` flag when I created the site but images still don't seem to be loading. Is there something I'm missing?

**Comment by bradp** [comment]
You'll also need to pass in the `--live-url` or `-u` flag.

That could be documented better.

**Comment by thenoelforte** [comment]
If VV prompts me for the live URL should proxying still work? Or do I specifically have to pass in a live URL? Also, is there any way to rebuild a site without destroying the database, so if something was configured incorrectly I could fix it?

**Comment by bradp** [comment]
There may be a bug in the way the images proxy works. I'm planning on replacing it with another method.
When it prompts you for the live-url, that should work.

To rebuild a site, you can just remove and re-create in VV, as we don't currently destroy the database on deletion.

**Comment by bradp** [comment]
This is what will be used in the next version: https://gist.github.com/gregrickaby/1dbdb784c525835a08c8

Feel free to try it out now.

**Comment by bradp** [comment]
Updated 6addeb221c5fd8e8f8e9bf4fbad80ee6d0fe886b.

Still needs a bit of testing before, but will be in the next release.
