### ISSUE TITLE
Error Adding Defines from Blueprint

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#69]
==> default: Adding constants to wp-config.php...
==> default: PHP Notice:  Undefined variable: path in /srv/www/Test/vv-install on line 65
==> default: PHP Notice:  Undefined variable: path in /srv/www/Test/vv-install on line 65
==> default: sed: can't read .//wp-config.php: No such file or directory

**Comment by bradp** [comment]
Fixed in 7909a70af80f
