### ISSUE TITLE
Admin Credentials Not Being Updated

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#70]
I passed the admin arguments into <code>vv create</code> and the username or password printed at the end of the create process, but the username and password in the database are just <code>admin</code> and <code>password</code>.

<code>
vv create  --username test --password test --email test@test.com
</code>

**Comment by bradp** [comment]
Just pushed a fix for this in 6700bfc12e6e.

This will be in the next version, releasing that tomorrow morning.

**Comment by clreed87** [comment]
Awesome. Thanks for the quick response. Sorry for opening so many issues!

**Comment by bradp** [comment]
No worries, I appreciate it actually!
