### ISSUE TITLE
Multiple Vagrant installs and HGV

### ISSUE THREAD

**Issue by jb510** [bradp/vv#72]
Sorry to ask questions as issues, but...

1) Can VV work with multiple vagrant installs? If so how? Is there documentation for that somewhere?
Seems like I either heard no somewhere or just it was complicted.

2) Anyone tried using this with WP Engine's HGV vagrant box instead of VVV?  

I'm trying to run VVV and HGV side by side which is no problem, but wishing I had the same tools for managing both and just haven't quite figured it all out yet.

**Comment by bradp** [comment]
You can use the -fp flag to pass in your second install's path on your system. Right now, that's the only way that's built in way to manage multiple installs. 

I could probably build out a way to name different environments, and manage more than one. 

Brad Parbs

**Comment by jb510** [comment]
Thanks! I hadn't noticed the -fp flag, I'll give that a try.

Personally I love that VV knows where my primary VVV install is...  just as I'm moving several WPE sites into HGV I wanted an easy way...  I don't mind typing a few extra characters.

**Comment by jb510** [comment]
I figured out how to use -fp. But it doesn't work with hgv [https://github.com/wpengine/hgv] because VV assume path/www, whereas hgv uses /hgv/hgv_data/sites/

Being command line comfortable, but far from expert.  A few more examples of using vv's options would be helpful.  I'd assumed something like vv -fp "path", or vv -fp "path" create.  

± % vv -fp create
VVV install directory: hgv-test
...
Create directory hgv-test in /Users/jon/hgv/www

**Comment by jb510** [comment]
I started forking VV with the thought of a separate version for HGV, but quickly realized that was a dumb was to do it and instead made the web root into a varible.

Not a smoothly working finished product, but an idea:
https://github.com/jb510/vv/commit/dc7f22973ec71a604b5fc0bd5cdad245a54d2226

I'm currently manually setting values in .vv-config to toggle between the two, but it's getting closer.

**Comment by bradp** [comment]
Hey @jb510, finally getting to this issue now.

I'm looking through your forked version, and can implement the idea into VV. I'm curious if you've gotten HGV working with multiple sites?

**Comment by bradp** [comment]
I've added experimental support for this.

You can do `vv create --force-path --force-sites-folder my_sites_folder` and then use your HGV root for the first prompt, which will ask for your path to HGV (normally VVV).

Not sure how creation works with HGV, but this should be all VV needs to do to get it working.

**Comment by jb510** [comment]
Thanks Brad. I'll check it out today.

FWIW, HGV has no provision for adding sites baked in yet: https://github.com/wpengine/hgv/issues/44

While it should be possible to add sites manually (cp nginx.conf, etc..)  HGV uses  different nginx config setup/location than I'm used to so I stumbled around bit and didn't quite get it figured out.   I've also been playing with Wocker.  I have Docker dreams...  

I'll report back if this works at least getting the site cloned/created in HGV.  I'm assuming I'll still need to manually create the conf.
