### ISSUE TITLE
WordPress in its own directory.

### ISSUE THREAD

**Issue by boldfish** [bradp/vv#73]
I'd like to install wordpress in a directory below root, yet have it serve pages at root level.  (http://codex.wordpress.org/Giving_WordPress_Its_Own_Directory)  any way I can automate that with vv?  I might have missed the significance of the vv create options, is it possible?

**Comment by bradp** [comment]
Currently, there isn't a way to automate this.

I'll be adding this functionality to close https://github.com/bradp/vv/issues/46, though.
