### ISSUE TITLE
Add option for creating db with blank sites

### ISSUE THREAD

**Issue by mattbanks** [bradp/vv#76]
Looking for a way to scaffold out a new site where I'm going to be pulling in a current BackupBuddy backup (or similar) from a live site. I know I can run `vv create --blank` and it'll create the site and domains, but then I still have to go in and create the database manually. Any chance of adding an option flag for creating a blank database if you pass the `--blank` fag?

**Comment by bradp** [comment]
Added in 9231da09ff671af892ed58f687db4f49c147a327. There's a new flag ``--blank-with-db``, so you'd do ``vv create --blank-with-db``. This will be in the next released version, coming soon.

**Comment by mattbanks** [comment]
Awesome - thanks!
