### ISSUE TITLE
Creating Multiple Sites [REQUEST]

### ISSUE THREAD

**Issue by shaneholloman** [bradp/vv#78]
Currently am using for single sites and is great!
What is the method creating multilple sites locally via `vv`?

*Example:*
```
littleriverband.dev
fuega.dev
kahi.dev
ultrapress.dev
yoyo.dev
tuesdaypro.dev
linamuses.dev
3dwurld.dev
unitedsaints.dev
chrisholloman.dev
katipocreative.dev
dame.dev
traffic.dev
iloveyouverymuch.dev
hearspeakhere.dev
loslonelyboys.dev
thedunwells.dev
playingintrafficrecords.dev
```

**Comment by bradp** [comment]
I'm not sure what you mean.
You'd like to create multiple sites at once? Or you just want to create multiple sites using VV?

If you'd like to just create multiple sites, you can just run the ``vv create`` command once for each site you'd like to set up.

**Comment by shaneholloman** [comment]
@bradp Sorry to be unclear

My intention is to create all sites at once with `vv` - If I add each separately the provision time is very lengthy and would take many hours to complete

Hope that make sense ...

**Comment by bradp** [comment]
That makes sense. Right now there isn't a way to do that, but I can add it sometime in the future.

In the mean time, you can use the ``--files`` flag to not provision Vagrant, so you could create all sites with that, and then provision once at the end.

**Comment by shaneholloman** [comment]
@bradp  `--files` Fantastic idea and a massive help. Thank you
