### ISSUE TITLE
Pass created site url to blueprints.

### ISSUE THREAD

**Issue by bradp** [bradp/vv#83]
From here: https://github.com/bradp/vv/issues/74

> Is there a way to use the domain entered in vv create in the blueprint? That way you could enter testsite.dev and have the following defines create automagically since the plugin requires them:
>
> define( 'WP_HOME', 'http://example.com' );
> define( 'WP_SITEURL', 'http://example.com' );

**Comment by 1bigidea** [comment]
I could use the same capability to auto-install Delicious Brain's WP DB Migrate plugin (which requires a domain in the url string to install (ala Composer) see https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/

**Comment by bradp** [comment]
This is now complete on the develop branch and will be in the next version.
