### ISSUE TITLE
Fully support HGV

### ISSUE THREAD

**Issue by bradp** [bradp/vv#84]
Let's get VV to fully support https://github.com/wpengine/hgv

In order to do this, it requires a solution here, most likely: https://github.com/wpengine/hgv/issues/44

**Comment by michaelbeil** [comment]
+1

**Comment by sc0ttkclark** [comment]
+1

**Comment by sc0ttkclark** [comment]
This is the only reason I'm not using HGV more, really want to check it out but site creation is balls.

**Comment by michaelbeil** [comment]
:100: for @sc0ttkclark

**Comment by jb510** [comment]
HGV now support multiple installs and setting up new sites isn't the bear it was...  still it's be nice to automate creation and tear down a bit more.  HGV uses yml playbooks though and seems like a completely different approach than VVV.  Wondering if it makes sense to support both, or fork VV into something new?

**Comment by JasonTheAdams** [comment]
+1

**Comment by bradp** [comment]
Closing this to track in the 2.0 release issue: https://github.com/bradp/vv/issues/161
