### ISSUE TITLE
More WP-CLI support through blueprints

### ISSUE THREAD

**Issue by Octopixell** [bradp/vv#85]
Hi @bradp after the stuff we worked through today I took the evening to have a go at rewriting `vv-blueprints.json` and the `vv-install` file in order to support the following WP-CLI command options:

* --version
* --force
* --activate
* --activate_network (This one is plugin only)

You can check my changes here: http://git.io/hLXx

As you can see in my fork I had to change the way the script works when a plugin or theme is retrieved based on the `user/repository` format. I've tested it and so far it works. All four methods of installing a plugin or theme with the blueprint should work:

* Cloning a git repository
* Downloading a zip file from a specified location
* Downloading a git repository based on username and repository name (heavily rewritten)
* Downloading the plugin from the WP Plugin repository based on the URL slug

I also added PHPDoc comment blocks for future development and some inline comments that make the script a little easier to read. Please let me know if you like the code changes or if you'd like something changed. When all is ready I can then make a pull-request. 

Do note, this is the first time I contribute to a project so bare with me :) looking forward to your feedback.

Regards,
Octopixell

**Comment by bradp** [comment]
Hey @Octopixell, that looks great! The Blueprints functionality for sure needs some love, I hacked it together pretty quickly.

Looking through your changes, they all look great. I haven't tested it yet, but I'm sure its working well.

The only thing we'll have to add before merging this in is some backwards-compatibility from the existing blueprints JSON files, as they should work fine. If you'd like to add that and then open a PR, I'd love to merge this in.

Thanks!

**Comment by Octopixell** [comment]
Oh, and before I forget. In `vv-install` you were using `is_bool()` to determine wether something was a boolean or not but that wasn't working properly as that function doesn't work when the boolean you're checking is actually a string (http://stackoverflow.com/questions/7336861/how-to-convert-string-to-boolean-php & http://php.net/manual/en/function.is-bool.php). I have changed it to a string comparison now and that fixed it. (It's also faster than `is_bool()` I believe, for what it matters).

**Comment by Octopixell** [comment]
@bradp I'm happy you like the changes :D 

I totally forgot about backwards compatibility, you're right! I'll have a look into that tomorrow, shouldn't be too hard :)

**Comment by Octopixell** [comment]
Just pushed changes to the repo, it now checks wether the plugin is defined as an object in the JSON file or just as a string. When it's defined as a string it will execute the old code block so older blueprints should not break now :)

**Comment by Octopixell** [comment]
@bradp I've taken the time to completely rewrite the `install()` function again for backwards compatibility and more inline documentation/explanation (I found my other solution simply too sloppy). Just tested it again and works smoothly. It now also shows the WP-CLI install options you've set when echoing feedback into the console too. Let me know when you've tested it too so i can do a PR :)

**Comment by bradp** [comment]
If you could, that would be great if you could submit a PR with it as it is, and I'll test it that way. Looks good so far, though.

**Comment by Octopixell** [comment]
@bradp just did a PR. Hope I did it properly, my first time doing one ;)
