### ISSUE TITLE
Xip.io support nginx domain incorrect

### ISSUE THREAD

**Issue by Octopixell** [bradp/vv#86]
Hi @bradp 

I found an issue with the extra xip.io domain for the nginx config.

Currently you're rewriting it as follows: `server_name sitename.dev ~^sitename.d+.d+.d+.d+.xip.io$;`
This is causing the VVV dashboard to load instead of the actual website.

If you rewrite it like this: `server_name sitename.dev ~^sitename\.\d+\.\d+\.\d+\.\d+\.xip\.io$;` things will work perfectly.

**Comment by bradp** [comment]
Fixed in 61336bb1af23.

**Comment by Octopixell** [comment]
@bradp just had the time to test this. All fixed, closing the issue.

**Comment by Octopixell** [comment]
@bradp did something change with this? The server names in the config files are back to `server_name  xipio.dev ~^xipio.d+.d+.d+.d+.xip.io$;` again instead of `server_name  xipio.dev ~^xipio.\.\d+\.\d+\.\d+\.\d+\.xip\.io$`

**Comment by bradp** [comment]
@Octopixell are you on the latest version? I created a new site yesterday, and checking the config, it is the correct one with the escaped stuff

**Comment by Octopixell** [comment]
@bradp I'll have a look in the morning and let you know. I do hope it's my own stupid mistake though haha.

**Comment by Octopixell** [comment]
@bradp I've completely reinstalled VV and it works again. Not sure what went wrong but it's fixed!
