### ISSUE TITLE
Deployments with Vagrant Push missing config for push.dir? 

### ISSUE THREAD

**Issue by Octopixell** [bradp/vv#89]
@bradp I just created a deployment with `vv` and it seems to be missing a prompt for the `push.dir` line of the config: ( https://docs.vagrantup.com/v2/push/ftp.html )

`dir` - The base directory containing the files to upload. **By default this is the same directory as the Vagrantfile**, but you can specify this if you have a `src` folder or `bin` folder or some other folder you want to upload.

An example of the config created by `vv` in my case:

```
#begin-vv-yourcontact-staging
    config.push.define "yourcontact-staging", strategy: "ftp" do |push|
        push.host ="***********************:22"
        push.username ="***********************"
        push.password ="***********************"
        push.passive ="true"
        push.secure ="true"
        push.destination ="***********************"
        push.dir = ""
        push.exclude = "wp-config.php"
    end
#end-vv-yourcontact-staging
```

Shouldn't `push.dir` be equal to `www/$sitename/htdocs`, in this case `www/yourcontact/htdocs`?

I'm asking since my deployments don't seem to do anything. When using `vv -v push yourcontact-staging` nothing seems to happen and no files actually appear on the staging server. Maybe there's a log that I don't know about which would show errors happening maybe?

**Comment by bradp** [comment]
Just pushed out version 1.7.2 that fixes this. In 1.7.0, I added some new methods to change the sites path, and deployments had a bug where it was using the old path variables.
