### ISSUE TITLE
Confused about Blueprints

### ISSUE THREAD

**Issue by ericthor** [bradp/vv#91]
When adding the blueprint option to the create command currently doesn't pull in the plugins and themes. I'm using the default vv-blueprint.json file. In my log I notice these two lines.

==> default: Setting up blueprint sample...
==> default: Blueprint setup.

It looks like it builds out the vv-install command in the site-directory, but that's it. What step am I missing. Is there another command I need to run? Limited experience with this any help appreciated.

**Comment by bradp** [comment]
There was a bug in the blueprints install mechanism that was just fixed yesterday. Can you create a new site and see if your issue persists?

**Comment by ericthor** [comment]
I'm running vv 1.7.2. according to  `vv --version` Installed via homebrew.

I ran the command `vv create` and indicated that I wanted to run the `sample` blueprint. That is found in my `vvv/vv-blueprints.json`.  The `vv-blueprints.json` file was auto created with the `vv --blueprint-init` command. 

After running `vv create` and indicating the blueprint and all the other site information it created the proper directory.

In that directory there is  a `htdocs` folder with a standard wordpress install. None of the themes or plugins from the `vv-blueprint.json`. It also created `wp-cli.yml`, `vvv-init.sh`, `vvv-hosts`, and `vv-install`.

The `vv-install` looks like it lists all the blueprint information. A few of the first lines.

````
function main( $blueprint, $path = 'htdocs' ) {
	echo "Setting up blueprint $blueprint...\n";
	$blueprints = json_decode( file_get_contents( "vv-blueprints.json" ) );

	if ( ! empty( $blueprints->$blueprint->themes ) ) {
		echo "Installing themes...\n";
		foreach ( $blueprints->$blueprint->themes as $theme ) {
			install( 'theme', $theme, $path );
		}
	}
````

The last bunch of lines in the log. It does note the `==> default: Setting up blueprint sample...` and `==> default: Blueprint set up`.

````
==> default: Success: WordPress downloaded.
==> default: Success: Generated wp-config.php file.
==> default: sendmail: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
==> default: postdrop: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
==> default: Success: WordPress installed successfully.
==> default: /srv/www/sample3
==> default: Setting up blueprint sample...
==> default: Blueprint set up.
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added sample.dev from /srv/www/sample/vvv-hosts
==> default:  * Added sample2.dev from /srv/www/sample2/vvv-hosts
==> default:  * Added sample3.dev from /srv/www/sample3/vvv-hosts
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 268 seconds
==> default: External network connection established, packages up to date.
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: mysql stop/waiting
==> default: mysql start/running, process 3977
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:  * Restarting nginx nginx
==> default:    ...done.
[Success] New VVV Site Setup: Done! 
````

If there is any other spec information that you need please let me know thank you very much for your help.

**Comment by bradp** [comment]
According to that log, it looks like it attempted to set up the blueprint.

Can you remove the entire htdocs folder and re-run vagrant provision, and see if that helps?

**Comment by ericthor** [comment]
I deleted the htdocs folder in the directory and ran vagrant provision and got this.

````
==> default: PHP Warning:  file_get_contents(vv-blueprints.json): failed to open stream: No such file or directory in /srv/www/sample3/vv-install on line 9
==> default: Blueprint set up.
==> default: rm: 
==> default: cannot remove ‘vv-blueprints.json’
==> default: : No such file or directory
````

I deleted the htdocs again and added the `vv-blueprints.json` file to the directory and ran `vagrant provision`.

I get.

````
==> default: Setting up blueprint sample...
==> default: Blueprint set up.
````

It removes the `vv-blueprints.json` file from the directory and adds the information to the `vv-install` file and installs a default wordpress install.

**Comment by bradp** [comment]
Looks like from that error that it can't read vv-blueprints.json, want to try recreating the site from scratch?

**Comment by ericthor** [comment]
Deleted everything, site, vvv, vv. Cloned in vvv, brew installed vv. Ran `vv --blueprint-init`. Ran `vv create`. Selected sample blueprint. It installed the default Wordpress install.

````
==> default: Downloading phpMyAdmin 4.2.13.1...
==> default: Installing WordPress (release version) in sample/htdocs...
==> default: Downloading WordPress 4.1.1 (en_US)...
==> default: Success: WordPress downloaded.
==> default: Success: Generated wp-config.php file.
==> default: Success: WordPress installed successfully.
==> default: /srv/www/sample
==> default: Setting up blueprint sample...
==> default: Blueprint set up.
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added sample.dev from /srv/www/sample/vvv-hosts
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 1207 seconds
==> default: External network connection established, packages up to date.
==> default: For further setup instructions, visit http://vvv.dev
````

Are their certain dependencies I might not have?
Should I maybe try an older version of vv?
Thanks again for all your help really appreciate it.

**Comment by bradp** [comment]
Still not working? I'd say remove your current vv-blueprints.json file in your main VVV folder, re run blueprints-init, and then try again.

**Comment by ericthor** [comment]
Still the same. You haven't been able to replicate this have you? I should be seeing this in the log I guess?

````
<?php
#/usr/bin/php
/**
 * @param $blueprint
 * @param string $path
 */
function main( $blueprint, $path = 'htdocs' ) {
	echo "Setting up blueprint $blueprint...\n";
	$blueprints = json_decode( file_get_contents( "vv-blueprints.json" ) );

	if ( ! empty( $blueprints->$blueprint->themes ) ) {
		echo "Installing themes...\n";
		foreach ( $blueprints->$blueprint->themes as $theme ) {
			install( 'theme', $theme, $path );
		}
	}
	if ( ! empty( $blueprints->$blueprint->plugins ) ) {
		echo "Installing plugins...\n";
		foreach ( $blueprints->$blueprint->plugins as $plugin ) {
			install( 'plugin', $plugin, $path );
		}
	}
	if ( ! empty( $blueprints->$blueprint->mu_plugins ) ) {
		echo "Installing mu-plugins...\n";
		foreach ( $blueprints->$blueprint->mu_plugins as $mu_plugin ) {
            install( 'mu-plugin', $mu_plugin, $path );
        }
    }
    if ( ! empty( $blueprints->$blueprint->options ) ) {
        echo "Setting up options...\n";
        foreach( $blueprints->$blueprint->options as $option ) {
            add_option( $option );
        }
    }
    if ( ! empty( $blueprints->$blueprint->defines ) ) {
        echo "Adding constants to wp-config.php...";
        foreach( $blueprints->$blueprint->defines as $define ) {
            add_define( $define, $path );
        }
    }

    echo "Blueprint set up.\n";
}
````

I guess this skips all the !empty conditionals. Is there a way I could run this and get more information?

**Comment by kimmenbert** [comment]
I´m experiencing just the same.
==> default: Setting up blueprint sample...
==> default: Blueprint set up.

It then deletes the blueprint file from the new site root folder and it has had no impact on the wordpress setup

**Comment by bradp** [comment]
@kimmenbert @ericthor Can you two share you vvv-blueprints files please? 

I'm thinking its either an issue with it not being read correctly, or something not being passed to the vv-install helper script correctly.

**Comment by kimmenbert** [comment]
I´m doing a complete reinstall of vagrant and everything connected to it, will share the blueprints file if it fails again

**Comment by kimmenbert** [comment]
Didn´t work. Fresh install of virtualbox, vagrant, vv ...
Here is the file, this is not touched after doing vv blueprint-init:
https://github.com/kimmenbert/vv-blueprint/blob/master/vv-blueprints.json

**Comment by bradp** [comment]
Can you copy that to a site folder, vagrant ssh in and execute `curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install sample NAMEOFSITE && rm vv-blueprints.json` and let me know if it throws any errors? Thanks.

**Comment by kimmenbert** [comment]
vagrant@vvv:~$ curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install sample blueprinttest && rm vv-blueprints.json

Setting up blueprint sample...

PHP Warning:  file_get_contents(vv-blueprints.json): failed to open stream: No such file or directory in /home/vagrant/vv-install on line 9

Blueprint set up.

rm: cannot remove 'vv-blueprints.json': No such file or directory

**Comment by bradp** [comment]
Make sure you copy the vvv-blueprints.json file to that directory first.

**Comment by bradp** [comment]
And you'll want to execute it inside the folder of a site.

**Comment by kimmenbert** [comment]
```
vagrant@vvv:/vagrant/www/blueprinttest$ curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install sample blueprinttest && rm vv-blueprints.json

Setting up blueprint sample...
Blueprint set up.

vagrant@vvv:/vagrant/www/blueprinttest$ 
```

**Comment by kimmenbert** [comment]
Running:
- osx 10.10.2
- Vagrant 1.7.2 with hostupdater and vagrant triggers plugin
- VirtualBox 4.3.26 with VirtualBox 4.3.26 Oracle VM VirtualBox Extension Pack
- vv 1.7.2

**Comment by bradp** [comment]
@kimmenbert There have been some new improvements of blueprints lately. Can you verify these have fixed your issues?

**Comment by kimmenbert** [comment]
@bradp Seems to be working as intended now. Great! Thanks for the follow up

**Comment by ingageco** [comment]
@bradp I am having the same issue - still. I completed the steps above and blueprints started working, but now they've stopped again. Is this a fix for the issue, or a simple patch for one specific vv site to run the blueprint after the site is setup?

**Comment by zanematthew** [comment]
First let me thank @bradp and others that have contributed to this project. Its amazing.

My question is with the intended use for the `vv-blueprints.json` file.

I was under the impression that entering the command `vv create -b sample` would create a sample site using the default entry in the `vv-blueprints.json` file. 

Rather I was _still_ prompted to enter the "basic" information for creating a website. I later looked into the `vv-blueprints.json` file and realized that the information below was not present in the file.

```
$ vv create -b sample
New VVV Site Setup
 Name of new site directory: sample
 Domain to use (leave blank for sample.dev):
 WordPress version to install (leave blank for latest version or trunk for trunk/nightly version):
 Install as multisite? (y/N): N
 Git repo to clone as wp-content (leave blank to skip):
 Local SQL file to import for database (leave blank to skip):
 Remove default themes and plugins? (y/N): y
 Add sample content to site (y/N): y
 Enable WP_DEBUG and WP_DEBUG_LOG (y/N): y
```
Shouldn't this information be derived from the `vv-blueprints.json` file?

Also wouldn't this entry ` Add sample content to site (y/N): y` conflict with the line `demo_content` in the `vv-blueprints.json` file?
