### ISSUE TITLE
Blueprint can't enable plugins from .git URL

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#93]
With the new blueprint format one of my exiting plugins was downloading from a .git URL.  The plugin still downloaded properly but failed to activate via --activate.  Changed the plugin URL to the github .zip URL and activation worked as expected (expect my plugin directory has '-master' appened.

**Comment by clreed87** [comment]
Actually after some additional testing it won't activate even if I include the .zip in the blueprint.

**Comment by Octopixell** [comment]
@clreed87 Do you have a URL I can test this with? I'll have a look into it if you want.

**Comment by clreed87** [comment]
Sure. I just have a simple plugin with some custom code I use on client sites that I wanted to automatically install/activate:

https://github.com/clreed87/crt-plugin.git

**Comment by Octopixell** [comment]
@clreed87 perfect! Thanks for giving me a test URL. I'll have a look at this asap!

**Comment by clreed87** [comment]
Thanks! Let me know if there's anything you'd like me to test out!

**Comment by Octopixell** [comment]
@clreed87 I just created a pull request with a fix! :+1:

**Comment by bradp** [comment]
Closing as fixed, @clreed87 feel free to make a new issue if you see issues.

Thanks @Octopixell you are a rockstar!
