### ISSUE TITLE
Allow VV to create wildcard subdomain sites

### ISSUE THREAD

**Issue by bradp** [bradp/vv#94]

**Comment by lvgunst** [comment]
`$multisite_domains` on https://github.com/bradp/vv/blob/master/vv#L807 is undefined. Shouldn't this be something like `*.$domain`?

I don't think hosts files support wildcard domains. So for now you have to manually add subdomains to the `vvv-hosts` file of your multisite.

**Comment by bradp** [comment]
The original plan was to prompt for subdomain sites somehow and populate that list.

You are correct, there isn't a great way to do wildcard domains, and right now the process does need to be manually adding them to vvv-hosts and to ngnix config.

I think a way to add a new subdomain without manual editing is what vv really needs.

**Comment by michaelryanmcneill** [comment]
In my opinion, I think it would be best to have the nginx config account for the wildcard (`*.$domain`) and have the user add the domain to the hosts file manually. That is the way VVV does it by default (per: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/284#issuecomment-37112494), and I believe following their lead is the best way to offer as close to a resolution as possible.
