### ISSUE TITLE
Update checks fail when Github version not returned by `check_for_update()`.

### ISSUE THREAD

**Issue by morganestes** [bradp/vv#95]
Every command I run returns `Your version of vv does not match the current Github version. Please update with vv --update`, but I *am* running the most recent version (1.7.2 as of this issue). Looking at the code, [the line to set `$github_version`](https://github.com/bradp/vv/blob/1.7.2/vv#L172) returns an empty string, so the version check always fails.

A cursory stepping through tells me that `grep "\"name\": \""` isn't returning anything, so everything behind it fails, but I haven't gotten any further to know what to do differently.

**Comment by bradp** [comment]
Thanks, I'll check it out and see if I can repro.

I think I good fix might be to see if it fails more than a few times in a set period of time, and then suppress the message.

**Comment by bradp** [comment]
Just out of curiosity, what do you get if you run ``curl -s https://api.github.com/repos/bradp/vv/tags | grep "\"name\": \"" | head -n 1 | sed 's/"name": "//' | sed 's/",//' | sed 's/ //g' `` outside of vv?

**Comment by morganestes** [comment]
I get an empty line. That's how I tested the line itself to figure out that the initial grep wasn't getting the info we needed. The curl request returns the string with all the versions, so that part isn't an issue, but the parsing of it is the problem for me.

**Comment by bradp** [comment]
This should be fixed now in 2786f6e8e645, and will be in the next release.

**Comment by bradp** [comment]
This is now in version 1.8.0, which was just released.

**Comment by morganestes** [comment]
Just updated and confirmed it's fixed. Thanks!

**Comment by topdown** [comment]
I am having the same issue. vv --update downloads 1.7.2
Running cUrl against github says 1.9.3
