### ISSUE TITLE
How can I add my own theme's repos?

### ISSUE THREAD

**Issue by lmartins** [bradp/vv#96]
Hi,

What is the recommended approach to add my own themes, which are git repos themselves.
This os probably more related to Vagrant itself than VV, but I was hoping someone could point my in the right direction.

Thanks.

**Comment by bradp** [comment]
You can use [blueprints](https://github.com/bradp/vv#blueprints) for that.

**Comment by lmartins** [comment]
actually I need something that allows me to make changes and immediately see the results. 
I'll try to find a way to do it. Thanks

**Comment by bradp** [comment]
You can just clone your theme into a new site's wp-content folder and work on it there.

I don't quite understand the issue, to be honest.

**Comment by lmartins** [comment]
Hey Brad, sorry about my confusion. I thought i've read somewhere that I shouldn't make any changes inside the VM. Cloning my repo into the themes folder is what I need. Thanks again.
