### ISSUE TITLE
Bash auto completion

### ISSUE THREAD

**Issue by Mte90** [bradp/vv#99]
Is possible add this support?

**Comment by Octopixell** [comment]
Had a quick look and found this (Might help with the implementation):

* http://askubuntu.com/questions/68175/how-to-create-script-with-auto-complete
* http://www.gnu.org/software/bash/manual/bash.html#Programmable-Completion
* http://tldp.org/LDP/abs/html/tabexpansion.html
* http://www.debian-administration.org/article/316/An_introduction_to_bash_completion_part_1

**Comment by bradp** [comment]
There is an older issue that I've closed: https://github.com/bradp/vv/issues/12

Basically, its a lot of work to support this. Using brew for installation gives us the ability to modify the bash completions, but it still requires a lot of modification inside of vv. I think its doable, but its not a huge priority for me.

PRs are welcome for sure for any more basic support or scaffolding to make it more likely.

**Comment by Octopixell** [comment]
@bradp I have no experience with Bash script so I'm not sure how much I can be of help on this one. I'll have a read into it when I can. Was already doing a little research to maybe implement #83 

Also, there's not that many commands in VV (imho) so autocomplete is not ***that*** necessary :smile:

**Comment by bradp** [comment]
Yeah, there isn't that many commands, but it would be real nice to be able to autocomplete things like `vv remove` or stuff like that.

**Comment by Octopixell** [comment]
@bradp I'll see if I can learn Bash Script, would be handy for my own projects too :smile: Starting with: http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html. If you know any good resources let me know. Would like to help out wherever I can

**Comment by interglobalmedia** [comment]
@bradp Remember I emailed you about installing Homebrew on my Mac? And How I was having trouble? Well, installation is a lot simpler and different than what was shared on the website's homepage. The way Macs work now (I have a MacBook Pro from late 2013 and Yosemite installed) is that anything that isn't from an Apple Developer, is blocked from being installed. So you actually have to into preferences and then security and allow installation manually. I did that yesterday with another Application. This is new with Yosemite. Was not the case with Mavericks. So I have Homebrew up and running. Let's see what happens now. I will also log this info and add it to the documentation I am creating to make it easier for people to go through the process. I will then share the link here. Hope this helps in some way! Thanks for all you do!

**Comment by Mte90** [comment]
I can work on this but the concept is simple like this http://askubuntu.com/a/483149

A commando of vv that generate the list of the command to autocomplete ex: 'add remove create blabla' and the only things to do after is edit the example for the script path.

**Comment by bradp** [comment]
Yeah, the easy part is autocomplete for add, remove, create. the more difficult part is installation, as there are multiple ways to install vv. And if we're doing completions, I would really want to tab-complete site names into delete and also tab completion for other commands, like --webroot or --path.

**Comment by Mte90** [comment]
I think the simple is solution is create a gist and write in the readme the link and how to insert the autocompletion script.
many project use this solution for simplify the question :-)

**Comment by bradp** [comment]
Just pushed up a vv-completions file to the develop branch. Sourcing this in bash will add tab-completions to vv.

This doesn't work in zsh right now, so gonna leave this open until that works.

Also need to add instructions to the README.

**Comment by bradp** [comment]
This is now complete on the develop branch and will be in the next version.
